package com.yqwl.service;

import java.util.List;

import com.yqwl.Vo.AttentionVo;
import com.yqwl.pojo.Attention;

/**
 *
 * @ClassName: AttentionService
 * @description 用一句话描述这个类的作用
 *
 * @author linhongyu
 * @createDate 2019年4月11日
 */
public interface AttentionService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int insertSelective(Attention record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);
	
	Attention selectFinfAll(Attention record);
	
	List<AttentionVo> selectScend(AttentionVo records);
	
	List<AttentionVo> selectThird(AttentionVo records);
	
	Integer selectCount(AttentionVo records);
}
