package com.yqwl.service;

import com.yqwl.pojo.Broker;

/**
 *
 * @ClassName: BrokerService
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月11日
 */
public interface BrokerService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	Broker selectByPrimaryKey(Long id);
}
