package com.yqwl.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.github.pagehelper.PageInfo;
import com.yqwl.Vo.BuildingListVo;
import com.yqwl.Vo.BuildingVo;
import com.yqwl.Vo.MapBuildingVo;
import com.yqwl.common.utils.Pager;
import com.yqwl.pojo.Building;
public interface BuildingService {

	PageInfo<BuildingVo> listBuildingByCondition(Pager pager) throws Exception;

	PageInfo<BuildingVo> listByBuilding(Pager pager) throws Exception;

	Integer listByHouseCount(Integer cityId) throws Exception;

	BuildingVo getBuildingById(Long buildingId) throws Exception;
	List<MapBuildingVo> MapSelectBuilding(Integer cityId, Integer regionId, Integer startSpace, Integer endSpace, BigDecimal startMoney, BigDecimal endMoney, Integer fitment) throws Exception;
	/**
	 *
	 * @Title: selectBuil
	 * @description 通过id查询信息
	 *
	 * @param @param id
	 * @param @return    
	 * @return BuildingListVo    
	 *
	 * @author linhongyu
	 * @createDate 2019年4月15日
	 */
	BuildingListVo selectBuil(Long id) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int insertSelective(Building record) throws Exception;
	
	int updateByPrimaryKeySelective(Building record) throws Exception;
	
	Map<String, Object> selectByPrimaryKey(Long id) throws Exception;
	/**
	 * @Title: selectBuilding
	 * @description 通过城市查询商厦信息
	 * @param @param building
	 * @param @return    
	 * @return List<BuildingListVo>    
	 * @author linhongyu
	 * @createDate 2019年4月25日
	 */
	List<BuildingListVo> selectBuilding(BuildingListVo building) throws Exception;
	/**
	 * @Title: selectBuilding
	 * @description 通过城市查询商厦信息条数
	 * @param @param building
	 * @param @return    
	 * @return List<BuildingListVo>    
	 * @author linhongyu
	 * @createDate 2019年4月25日
	 */
	Integer selectContBuil(BuildingListVo building) throws Exception;
	/**
	 * @Title: deleteByPrimaryKey
	 * @description 删除一条商厦信息
	 * @param @param id
	 * @param @return
	 * @param @throws Exception    
	 * @return int    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	int deleteByPrimaryKey(Long id) throws Exception;

	List<Building> listAllByCityId(Long cityId) throws Exception;

	List<Building> listAllByRegionId(Long regionId) throws Exception;

	List<Building> listBybuildingByCity(Integer cityId) throws Exception;
}
