package com.yqwl.service;

import com.yqwl.pojo.Client;

/**
 *
 * @ClassName: ClientService
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月16日
 */
public interface ClientService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int insert(Client record);
	
	Client seleceFindId(Long phones);
}
