package com.yqwl.service;

import java.util.List;

import com.yqwl.Vo.JournalismVo;
import com.yqwl.pojo.Journalism;

/**
 *
 * @ClassName: JournalismService
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月12日
 */
public interface JournalismService {
	
	List<JournalismVo> selectJour(JournalismVo records);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_journalism
	 * @mbggenerated
	 */
	Journalism selectByPrimaryKey(Long id);
	/**
     * @description 修改当前新闻浏览量
     * @author linhongyu
     * @createDate 2019年4月14日
     */
	int updateByPrimaryKeySelective(Journalism record);
	/**
     * @description 查询上一篇 新闻
     * @author linhongyu
     * @createDate 2019年4月14日
     */
    Journalism selectPrevious(Journalism record);
    /**
     * @description 查询下一篇 新闻
     * @author linhongyu
     * @createDate 2019年4月14日
     */
    Journalism selectNext(Journalism record);
}
