package com.yqwl.Vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @ClassName: AttentionVo
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月17日
 */
public class AttentionVo implements Serializable{

	/**  字段的含义 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.user_phone
	 * @mbggenerated
	 */
	private Long user_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.attention_time
	 * @mbggenerated
	 */
	private Date attention_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.mansion_name
	 * @mbggenerated
	 */
	private String mansion_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.mansion_picture
	 * @mbggenerated
	 */
	private String mansion_picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_city_id
	 * @mbggenerated
	 */
	private Integer region_city_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_cityname
	 * @mbggenerated
	 */
	private String region_cityname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_id
	 * @mbggenerated
	 */
	private Integer region_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_name
	 * @mbggenerated
	 */
	private String region_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.office_space
	 * @mbggenerated
	 */
	private Integer office_space;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.office_space
	 * @mbggenerated 最大面积
	 */
	private Integer office_spaces;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.money
	 * @mbggenerated
	 */
	private BigDecimal money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.money_unit
	 * @mbggenerated
	 */
	private Integer money_unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.work_name
	 * @mbggenerated
	 */
	private String work_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.house_picture
	 * @mbggenerated
	 */
	private String house_picture;
	
	private Integer count;
	
	public Integer getCount() {
		return count;
	}
	public void setCount(Integer count) {
		this.count = count;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getUser_phone() {
		return user_phone;
	}
	public void setUser_phone(Long user_phone) {
		this.user_phone = user_phone;
	}
	public Long getHouses_new_id() {
		return houses_new_id;
	}
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}
	public Integer getType() {
		return type;
	}
	public void setType(Integer type) {
		this.type = type;
	}
	public Date getAttention_time() {
		return attention_time;
	}
	public void setAttention_time(Date attention_time) {
		this.attention_time = attention_time;
	}
	public String getMansion_name() {
		return mansion_name;
	}
	public void setMansion_name(String mansion_name) {
		this.mansion_name = mansion_name;
	}
	public String getMansion_picture() {
		return mansion_picture;
	}
	public void setMansion_picture(String mansion_picture) {
		this.mansion_picture = mansion_picture;
	}
	public Integer getRegion_city_id() {
		return region_city_id;
	}
	public void setRegion_city_id(Integer region_city_id) {
		this.region_city_id = region_city_id;
	}
	public String getRegion_cityname() {
		return region_cityname;
	}
	public void setRegion_cityname(String region_cityname) {
		this.region_cityname = region_cityname;
	}
	public Integer getRegion_id() {
		return region_id;
	}
	public void setRegion_id(Integer region_id) {
		this.region_id = region_id;
	}
	public String getRegion_name() {
		return region_name;
	}
	public void setRegion_name(String region_name) {
		this.region_name = region_name;
	}
	public Integer getOffice_space() {
		return office_space;
	}
	public void setOffice_space(Integer office_space) {
		this.office_space = office_space;
	}
	public Integer getOffice_spaces() {
		return office_spaces;
	}
	public void setOffice_spaces(Integer office_spaces) {
		this.office_spaces = office_spaces;
	}
	public BigDecimal getMoney() {
		return money;
	}
	public void setMoney(BigDecimal money) {
		this.money = money;
	}
	public Integer getMoney_unit() {
		return money_unit;
	}
	public void setMoney_unit(Integer money_unit) {
		this.money_unit = money_unit;
	}
	public String getWork_name() {
		return work_name;
	}
	public void setWork_name(String work_name) {
		this.work_name = work_name;
	}
	public String getHouse_picture() {
		return house_picture;
	}
	public void setHouse_picture(String house_picture) {
		this.house_picture = house_picture;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((attention_time == null) ? 0 : attention_time.hashCode());
		result = prime * result + ((count == null) ? 0 : count.hashCode());
		result = prime * result + ((house_picture == null) ? 0 : house_picture.hashCode());
		result = prime * result + ((houses_new_id == null) ? 0 : houses_new_id.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((mansion_name == null) ? 0 : mansion_name.hashCode());
		result = prime * result + ((mansion_picture == null) ? 0 : mansion_picture.hashCode());
		result = prime * result + ((money == null) ? 0 : money.hashCode());
		result = prime * result + ((money_unit == null) ? 0 : money_unit.hashCode());
		result = prime * result + ((office_space == null) ? 0 : office_space.hashCode());
		result = prime * result + ((office_spaces == null) ? 0 : office_spaces.hashCode());
		result = prime * result + ((region_city_id == null) ? 0 : region_city_id.hashCode());
		result = prime * result + ((region_cityname == null) ? 0 : region_cityname.hashCode());
		result = prime * result + ((region_id == null) ? 0 : region_id.hashCode());
		result = prime * result + ((region_name == null) ? 0 : region_name.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((user_phone == null) ? 0 : user_phone.hashCode());
		result = prime * result + ((work_name == null) ? 0 : work_name.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AttentionVo other = (AttentionVo) obj;
		if (attention_time == null) {
			if (other.attention_time != null)
				return false;
		} else if (!attention_time.equals(other.attention_time))
			return false;
		if (count == null) {
			if (other.count != null)
				return false;
		} else if (!count.equals(other.count))
			return false;
		if (house_picture == null) {
			if (other.house_picture != null)
				return false;
		} else if (!house_picture.equals(other.house_picture))
			return false;
		if (houses_new_id == null) {
			if (other.houses_new_id != null)
				return false;
		} else if (!houses_new_id.equals(other.houses_new_id))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (mansion_name == null) {
			if (other.mansion_name != null)
				return false;
		} else if (!mansion_name.equals(other.mansion_name))
			return false;
		if (mansion_picture == null) {
			if (other.mansion_picture != null)
				return false;
		} else if (!mansion_picture.equals(other.mansion_picture))
			return false;
		if (money == null) {
			if (other.money != null)
				return false;
		} else if (!money.equals(other.money))
			return false;
		if (money_unit == null) {
			if (other.money_unit != null)
				return false;
		} else if (!money_unit.equals(other.money_unit))
			return false;
		if (office_space == null) {
			if (other.office_space != null)
				return false;
		} else if (!office_space.equals(other.office_space))
			return false;
		if (office_spaces == null) {
			if (other.office_spaces != null)
				return false;
		} else if (!office_spaces.equals(other.office_spaces))
			return false;
		if (region_city_id == null) {
			if (other.region_city_id != null)
				return false;
		} else if (!region_city_id.equals(other.region_city_id))
			return false;
		if (region_cityname == null) {
			if (other.region_cityname != null)
				return false;
		} else if (!region_cityname.equals(other.region_cityname))
			return false;
		if (region_id == null) {
			if (other.region_id != null)
				return false;
		} else if (!region_id.equals(other.region_id))
			return false;
		if (region_name == null) {
			if (other.region_name != null)
				return false;
		} else if (!region_name.equals(other.region_name))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		if (user_phone == null) {
			if (other.user_phone != null)
				return false;
		} else if (!user_phone.equals(other.user_phone))
			return false;
		if (work_name == null) {
			if (other.work_name != null)
				return false;
		} else if (!work_name.equals(other.work_name))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "AttentionVo [id=" + id + ", user_phone=" + user_phone + ", houses_new_id=" + houses_new_id + ", type="
				+ type + ", attention_time=" + attention_time + ", mansion_name=" + mansion_name + ", mansion_picture="
				+ mansion_picture + ", region_city_id=" + region_city_id + ", region_cityname=" + region_cityname
				+ ", region_id=" + region_id + ", region_name=" + region_name + ", office_space=" + office_space
				+ ", office_spaces=" + office_spaces + ", money=" + money + ", money_unit=" + money_unit
				+ ", work_name=" + work_name + ", house_picture=" + house_picture + ", count=" + count + "]";
	}
	
}
