
package com.yqwl.Vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * @ClassName: EntrustseeVo
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月10日
 */
public class EntrustseeVo implements Serializable{

	/**  字段的含义 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.broker_id
	 * @mbggenerated
	 */
	private Long broker_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.seetype
	 * @mbggenerated
	 */
	private Integer seetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.pleasetime
	 * @mbggenerated
	 */
	private Date pleasetime;
	/** 页数 */
	private int page=0;
	/** 分页条数 */
	private int limit=5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_houses_new.work_name
	 * @mbggenerated
	 */
	private String work_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.phone_number
	 * @mbggenerated
	 */
	private Long phone_number;
	
	public Long getPhone_number() {
		return phone_number;
	}
	public void setPhone_number(Long phone_number) {
		this.phone_number = phone_number;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getHouses_new_id() {
		return houses_new_id;
	}
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}
	public Long getBroker_id() {
		return broker_id;
	}
	public void setBroker_id(Long broker_id) {
		this.broker_id = broker_id;
	}
	public Integer getSeetype() {
		return seetype;
	}
	public void setSeetype(Integer seetype) {
		this.seetype = seetype;
	}
	public Date getPleasetime() {
		return pleasetime;
	}
	public void setPleasetime(Date pleasetime) {
		this.pleasetime = pleasetime;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public int getLimit() {
		return limit;
	}
	public void setLimit(int limit) {
		this.limit = limit;
	}
	public String getWork_name() {
		return work_name;
	}
	public void setWork_name(String work_name) {
		this.work_name = work_name;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((broker_id == null) ? 0 : broker_id.hashCode());
		result = prime * result + ((houses_new_id == null) ? 0 : houses_new_id.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + limit;
		result = prime * result + page;
		result = prime * result + ((phone_number == null) ? 0 : phone_number.hashCode());
		result = prime * result + ((pleasetime == null) ? 0 : pleasetime.hashCode());
		result = prime * result + ((seetype == null) ? 0 : seetype.hashCode());
		result = prime * result + ((work_name == null) ? 0 : work_name.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EntrustseeVo other = (EntrustseeVo) obj;
		if (broker_id == null) {
			if (other.broker_id != null)
				return false;
		} else if (!broker_id.equals(other.broker_id))
			return false;
		if (houses_new_id == null) {
			if (other.houses_new_id != null)
				return false;
		} else if (!houses_new_id.equals(other.houses_new_id))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (limit != other.limit)
			return false;
		if (page != other.page)
			return false;
		if (phone_number == null) {
			if (other.phone_number != null)
				return false;
		} else if (!phone_number.equals(other.phone_number))
			return false;
		if (pleasetime == null) {
			if (other.pleasetime != null)
				return false;
		} else if (!pleasetime.equals(other.pleasetime))
			return false;
		if (seetype == null) {
			if (other.seetype != null)
				return false;
		} else if (!seetype.equals(other.seetype))
			return false;
		if (work_name == null) {
			if (other.work_name != null)
				return false;
		} else if (!work_name.equals(other.work_name))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "EntrustseeVo [id=" + id + ", houses_new_id=" + houses_new_id + ", broker_id=" + broker_id + ", seetype="
				+ seetype + ", pleasetime=" + pleasetime + ", page=" + page + ", limit=" + limit + ", work_name="
				+ work_name + ", phone_number=" + phone_number + "]";
	}
	
}
