package com.yqwl.Vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * @ClassName: JournalismVo
 * @description 用一句话描述这个类的作用
 *
 * @author 姓名全拼
 * @createDate 2019年4月12日
 */
public class JournalismVo implements Serializable{

	/**  字段的含义 */
	private static final long serialVersionUID = 1L;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.genre
     *
     * @mbggenerated
     */
    private Integer genre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.page_view
     *
     * @mbggenerated
     */
    private Long page_view;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journalism.content
     *
     * @mbggenerated
     */
    private String content;
    /** 页数 */
	private int page;
	/** 分页条数 */
	private int limit;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Integer getGenre() {
		return genre;
	}
	public void setGenre(Integer genre) {
		this.genre = genre;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public Date getTime() {
		return time;
	}
	public void setTime(Date time) {
		this.time = time;
	}
	public Long getPage_view() {
		return page_view;
	}
	public void setPage_view(Long page_view) {
		this.page_view = page_view;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public int getLimit() {
		return limit;
	}
	public void setLimit(int limit) {
		this.limit = limit;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	@Override
	public String toString() {
		return "JournalismVo [id=" + id + ", genre=" + genre + ", title=" + title + ", source=" + source + ", time="
				+ time + ", page_view=" + page_view + ", content=" + content + ", page=" + page + ", limit=" + limit
				+ "]";
	}
	
}
