package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Administrator implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.reality_name
	 * @mbggenerated
	 */
	private String reality_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.lock_status
	 * @mbggenerated
	 */
	private Byte lock_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.last_login_time
	 * @mbggenerated
	 */
	private Date last_login_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_administrator.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.id
	 * @return  the value of t_administrator.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.id
	 * @param id  the value for t_administrator.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.name
	 * @return  the value of t_administrator.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.name
	 * @param name  the value for t_administrator.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.password
	 * @return  the value of t_administrator.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.password
	 * @param password  the value for t_administrator.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.reality_name
	 * @return  the value of t_administrator.reality_name
	 * @mbggenerated
	 */
	public String getReality_name() {
		return reality_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.reality_name
	 * @param reality_name  the value for t_administrator.reality_name
	 * @mbggenerated
	 */
	public void setReality_name(String reality_name) {
		this.reality_name = reality_name == null ? null : reality_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.mobile
	 * @return  the value of t_administrator.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.mobile
	 * @param mobile  the value for t_administrator.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.lock_status
	 * @return  the value of t_administrator.lock_status
	 * @mbggenerated
	 */
	public Byte getLock_status() {
		return lock_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.lock_status
	 * @param lock_status  the value for t_administrator.lock_status
	 * @mbggenerated
	 */
	public void setLock_status(Byte lock_status) {
		this.lock_status = lock_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.last_login_time
	 * @return  the value of t_administrator.last_login_time
	 * @mbggenerated
	 */
	public Date getLast_login_time() {
		return last_login_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.last_login_time
	 * @param last_login_time  the value for t_administrator.last_login_time
	 * @mbggenerated
	 */
	public void setLast_login_time(Date last_login_time) {
		this.last_login_time = last_login_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_administrator.time
	 * @return  the value of t_administrator.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_administrator.time
	 * @param time  the value for t_administrator.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Administrator other = (Administrator) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getReality_name() == null ? other.getReality_name() == null
						: this.getReality_name().equals(other.getReality_name()))
				&& (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
				&& (this.getLock_status() == null ? other.getLock_status() == null
						: this.getLock_status().equals(other.getLock_status()))
				&& (this.getLast_login_time() == null ? other.getLast_login_time() == null
						: this.getLast_login_time().equals(other.getLast_login_time()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
		result = prime * result + ((getReality_name() == null) ? 0 : getReality_name().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getLock_status() == null) ? 0 : getLock_status().hashCode());
		result = prime * result + ((getLast_login_time() == null) ? 0 : getLast_login_time().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", password=").append(password);
		sb.append(", reality_name=").append(reality_name);
		sb.append(", mobile=").append(mobile);
		sb.append(", lock_status=").append(lock_status);
		sb.append(", last_login_time=").append(last_login_time);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}