package com.yqwl.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Attention implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.client_id
	 * @mbggenerated
	 */
	private Long client_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_attention.attention_time
	 * @mbggenerated
	 */
	private BigDecimal attention_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_attention
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_attention.id
	 * @return  the value of t_attention.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_attention.id
	 * @param id  the value for t_attention.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_attention.client_id
	 * @return  the value of t_attention.client_id
	 * @mbggenerated
	 */
	public Long getClient_id() {
		return client_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_attention.client_id
	 * @param client_id  the value for t_attention.client_id
	 * @mbggenerated
	 */
	public void setClient_id(Long client_id) {
		this.client_id = client_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_attention.houses_new_id
	 * @return  the value of t_attention.houses_new_id
	 * @mbggenerated
	 */
	public Long getHouses_new_id() {
		return houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_attention.houses_new_id
	 * @param houses_new_id  the value for t_attention.houses_new_id
	 * @mbggenerated
	 */
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_attention.attention_time
	 * @return  the value of t_attention.attention_time
	 * @mbggenerated
	 */
	public BigDecimal getAttention_time() {
		return attention_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_attention.attention_time
	 * @param attention_time  the value for t_attention.attention_time
	 * @mbggenerated
	 */
	public void setAttention_time(BigDecimal attention_time) {
		this.attention_time = attention_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Attention other = (Attention) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getClient_id() == null ? other.getClient_id() == null
						: this.getClient_id().equals(other.getClient_id()))
				&& (this.getHouses_new_id() == null ? other.getHouses_new_id() == null
						: this.getHouses_new_id().equals(other.getHouses_new_id()))
				&& (this.getAttention_time() == null ? other.getAttention_time() == null
						: this.getAttention_time().equals(other.getAttention_time()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getClient_id() == null) ? 0 : getClient_id().hashCode());
		result = prime * result + ((getHouses_new_id() == null) ? 0 : getHouses_new_id().hashCode());
		result = prime * result + ((getAttention_time() == null) ? 0 : getAttention_time().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", client_id=").append(client_id);
		sb.append(", houses_new_id=").append(houses_new_id);
		sb.append(", attention_time=").append(attention_time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}