package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Broker implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.real_name
	 * @mbggenerated
	 */
	private String real_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.user_name
	 * @mbggenerated
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.phonemunber
	 * @mbggenerated
	 */
	private Byte phonemunber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.birthday
	 * @mbggenerated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.shop_id
	 * @mbggenerated
	 */
	private Long shop_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.roles_id
	 * @mbggenerated
	 */
	private Long roles_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.state
	 * @mbggenerated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broker.picture
	 * @mbggenerated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_broker
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.id
	 * @return  the value of t_broker.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.id
	 * @param id  the value for t_broker.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.real_name
	 * @return  the value of t_broker.real_name
	 * @mbggenerated
	 */
	public String getReal_name() {
		return real_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.real_name
	 * @param real_name  the value for t_broker.real_name
	 * @mbggenerated
	 */
	public void setReal_name(String real_name) {
		this.real_name = real_name == null ? null : real_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.user_name
	 * @return  the value of t_broker.user_name
	 * @mbggenerated
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.user_name
	 * @param user_name  the value for t_broker.user_name
	 * @mbggenerated
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name == null ? null : user_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.password
	 * @return  the value of t_broker.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.password
	 * @param password  the value for t_broker.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.phonemunber
	 * @return  the value of t_broker.phonemunber
	 * @mbggenerated
	 */
	public Byte getPhonemunber() {
		return phonemunber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.phonemunber
	 * @param phonemunber  the value for t_broker.phonemunber
	 * @mbggenerated
	 */
	public void setPhonemunber(Byte phonemunber) {
		this.phonemunber = phonemunber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.birthday
	 * @return  the value of t_broker.birthday
	 * @mbggenerated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.birthday
	 * @param birthday  the value for t_broker.birthday
	 * @mbggenerated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.shop_id
	 * @return  the value of t_broker.shop_id
	 * @mbggenerated
	 */
	public Long getShop_id() {
		return shop_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.shop_id
	 * @param shop_id  the value for t_broker.shop_id
	 * @mbggenerated
	 */
	public void setShop_id(Long shop_id) {
		this.shop_id = shop_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.roles_id
	 * @return  the value of t_broker.roles_id
	 * @mbggenerated
	 */
	public Long getRoles_id() {
		return roles_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.roles_id
	 * @param roles_id  the value for t_broker.roles_id
	 * @mbggenerated
	 */
	public void setRoles_id(Long roles_id) {
		this.roles_id = roles_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.state
	 * @return  the value of t_broker.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.state
	 * @param state  the value for t_broker.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broker.picture
	 * @return  the value of t_broker.picture
	 * @mbggenerated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broker.picture
	 * @param picture  the value for t_broker.picture
	 * @mbggenerated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Broker other = (Broker) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getReal_name() == null ? other.getReal_name() == null
						: this.getReal_name().equals(other.getReal_name()))
				&& (this.getUser_name() == null ? other.getUser_name() == null
						: this.getUser_name().equals(other.getUser_name()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getPhonemunber() == null ? other.getPhonemunber() == null
						: this.getPhonemunber().equals(other.getPhonemunber()))
				&& (this.getBirthday() == null ? other.getBirthday() == null
						: this.getBirthday().equals(other.getBirthday()))
				&& (this.getShop_id() == null ? other.getShop_id() == null
						: this.getShop_id().equals(other.getShop_id()))
				&& (this.getRoles_id() == null ? other.getRoles_id() == null
						: this.getRoles_id().equals(other.getRoles_id()))
				&& (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
				&& (this.getPicture() == null ? other.getPicture() == null
						: this.getPicture().equals(other.getPicture()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getReal_name() == null) ? 0 : getReal_name().hashCode());
		result = prime * result + ((getUser_name() == null) ? 0 : getUser_name().hashCode());
		result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
		result = prime * result + ((getPhonemunber() == null) ? 0 : getPhonemunber().hashCode());
		result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
		result = prime * result + ((getShop_id() == null) ? 0 : getShop_id().hashCode());
		result = prime * result + ((getRoles_id() == null) ? 0 : getRoles_id().hashCode());
		result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
		result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", real_name=").append(real_name);
		sb.append(", user_name=").append(user_name);
		sb.append(", password=").append(password);
		sb.append(", phonemunber=").append(phonemunber);
		sb.append(", birthday=").append(birthday);
		sb.append(", shop_id=").append(shop_id);
		sb.append(", roles_id=").append(roles_id);
		sb.append(", state=").append(state);
		sb.append(", picture=").append(picture);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}