package com.yqwl.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Building implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.mansion_name
	 * @mbggenerated
	 */
	private String mansion_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.mansion_picture
	 * @mbggenerated
	 */
	private String mansion_picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_sh_id
	 * @mbggenerated
	 */
	private Integer region_sh_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_shname
	 * @mbggenerated
	 */
	private String region_shname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_city_id
	 * @mbggenerated
	 */
	private Integer region_city_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_cityname
	 * @mbggenerated
	 */
	private String region_cityname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_id
	 * @mbggenerated
	 */
	private Integer region_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.region_name
	 * @mbggenerated
	 */
	private String region_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.district
	 * @mbggenerated
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.floor
	 * @mbggenerated
	 */
	private Integer floor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.traffic_condition
	 * @mbggenerated
	 */
	private String traffic_condition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.activate_time
	 * @mbggenerated
	 */
	private Date activate_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.property_fee
	 * @mbggenerated
	 */
	private BigDecimal property_fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.parking_fee
	 * @mbggenerated
	 */
	private BigDecimal parking_fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.conditioners_fee
	 * @mbggenerated
	 */
	private BigDecimal conditioners_fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.intro
	 * @mbggenerated
	 */
	private String intro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.circum
	 * @mbggenerated
	 */
	private String circum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.longitude
	 * @mbggenerated
	 */
	private String longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_building.latitude
	 * @mbggenerated
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_building
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.id
	 * @return  the value of t_building.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.id
	 * @param id  the value for t_building.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.mansion_name
	 * @return  the value of t_building.mansion_name
	 * @mbggenerated
	 */
	public String getMansion_name() {
		return mansion_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.mansion_name
	 * @param mansion_name  the value for t_building.mansion_name
	 * @mbggenerated
	 */
	public void setMansion_name(String mansion_name) {
		this.mansion_name = mansion_name == null ? null : mansion_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.mansion_picture
	 * @return  the value of t_building.mansion_picture
	 * @mbggenerated
	 */
	public String getMansion_picture() {
		return mansion_picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.mansion_picture
	 * @param mansion_picture  the value for t_building.mansion_picture
	 * @mbggenerated
	 */
	public void setMansion_picture(String mansion_picture) {
		this.mansion_picture = mansion_picture == null ? null : mansion_picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_sh_id
	 * @return  the value of t_building.region_sh_id
	 * @mbggenerated
	 */
	public Integer getRegion_sh_id() {
		return region_sh_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_sh_id
	 * @param region_sh_id  the value for t_building.region_sh_id
	 * @mbggenerated
	 */
	public void setRegion_sh_id(Integer region_sh_id) {
		this.region_sh_id = region_sh_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_shname
	 * @return  the value of t_building.region_shname
	 * @mbggenerated
	 */
	public String getRegion_shname() {
		return region_shname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_shname
	 * @param region_shname  the value for t_building.region_shname
	 * @mbggenerated
	 */
	public void setRegion_shname(String region_shname) {
		this.region_shname = region_shname == null ? null : region_shname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_city_id
	 * @return  the value of t_building.region_city_id
	 * @mbggenerated
	 */
	public Integer getRegion_city_id() {
		return region_city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_city_id
	 * @param region_city_id  the value for t_building.region_city_id
	 * @mbggenerated
	 */
	public void setRegion_city_id(Integer region_city_id) {
		this.region_city_id = region_city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_cityname
	 * @return  the value of t_building.region_cityname
	 * @mbggenerated
	 */
	public String getRegion_cityname() {
		return region_cityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_cityname
	 * @param region_cityname  the value for t_building.region_cityname
	 * @mbggenerated
	 */
	public void setRegion_cityname(String region_cityname) {
		this.region_cityname = region_cityname == null ? null : region_cityname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_id
	 * @return  the value of t_building.region_id
	 * @mbggenerated
	 */
	public Integer getRegion_id() {
		return region_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_id
	 * @param region_id  the value for t_building.region_id
	 * @mbggenerated
	 */
	public void setRegion_id(Integer region_id) {
		this.region_id = region_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.region_name
	 * @return  the value of t_building.region_name
	 * @mbggenerated
	 */
	public String getRegion_name() {
		return region_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.region_name
	 * @param region_name  the value for t_building.region_name
	 * @mbggenerated
	 */
	public void setRegion_name(String region_name) {
		this.region_name = region_name == null ? null : region_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.district
	 * @return  the value of t_building.district
	 * @mbggenerated
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.district
	 * @param district  the value for t_building.district
	 * @mbggenerated
	 */
	public void setDistrict(String district) {
		this.district = district == null ? null : district.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.floor
	 * @return  the value of t_building.floor
	 * @mbggenerated
	 */
	public Integer getFloor() {
		return floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.floor
	 * @param floor  the value for t_building.floor
	 * @mbggenerated
	 */
	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.traffic_condition
	 * @return  the value of t_building.traffic_condition
	 * @mbggenerated
	 */
	public String getTraffic_condition() {
		return traffic_condition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.traffic_condition
	 * @param traffic_condition  the value for t_building.traffic_condition
	 * @mbggenerated
	 */
	public void setTraffic_condition(String traffic_condition) {
		this.traffic_condition = traffic_condition == null ? null : traffic_condition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.activate_time
	 * @return  the value of t_building.activate_time
	 * @mbggenerated
	 */
	public Date getActivate_time() {
		return activate_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.activate_time
	 * @param activate_time  the value for t_building.activate_time
	 * @mbggenerated
	 */
	public void setActivate_time(Date activate_time) {
		this.activate_time = activate_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.property_fee
	 * @return  the value of t_building.property_fee
	 * @mbggenerated
	 */
	public BigDecimal getProperty_fee() {
		return property_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.property_fee
	 * @param property_fee  the value for t_building.property_fee
	 * @mbggenerated
	 */
	public void setProperty_fee(BigDecimal property_fee) {
		this.property_fee = property_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.parking_fee
	 * @return  the value of t_building.parking_fee
	 * @mbggenerated
	 */
	public BigDecimal getParking_fee() {
		return parking_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.parking_fee
	 * @param parking_fee  the value for t_building.parking_fee
	 * @mbggenerated
	 */
	public void setParking_fee(BigDecimal parking_fee) {
		this.parking_fee = parking_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.conditioners_fee
	 * @return  the value of t_building.conditioners_fee
	 * @mbggenerated
	 */
	public BigDecimal getConditioners_fee() {
		return conditioners_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.conditioners_fee
	 * @param conditioners_fee  the value for t_building.conditioners_fee
	 * @mbggenerated
	 */
	public void setConditioners_fee(BigDecimal conditioners_fee) {
		this.conditioners_fee = conditioners_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.intro
	 * @return  the value of t_building.intro
	 * @mbggenerated
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.intro
	 * @param intro  the value for t_building.intro
	 * @mbggenerated
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.circum
	 * @return  the value of t_building.circum
	 * @mbggenerated
	 */
	public String getCircum() {
		return circum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.circum
	 * @param circum  the value for t_building.circum
	 * @mbggenerated
	 */
	public void setCircum(String circum) {
		this.circum = circum == null ? null : circum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.longitude
	 * @return  the value of t_building.longitude
	 * @mbggenerated
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.longitude
	 * @param longitude  the value for t_building.longitude
	 * @mbggenerated
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_building.latitude
	 * @return  the value of t_building.latitude
	 * @mbggenerated
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_building.latitude
	 * @param latitude  the value for t_building.latitude
	 * @mbggenerated
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Building other = (Building) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getMansion_name() == null ? other.getMansion_name() == null
						: this.getMansion_name().equals(other.getMansion_name()))
				&& (this.getMansion_picture() == null ? other.getMansion_picture() == null
						: this.getMansion_picture().equals(other.getMansion_picture()))
				&& (this.getRegion_sh_id() == null ? other.getRegion_sh_id() == null
						: this.getRegion_sh_id().equals(other.getRegion_sh_id()))
				&& (this.getRegion_shname() == null ? other.getRegion_shname() == null
						: this.getRegion_shname().equals(other.getRegion_shname()))
				&& (this.getRegion_city_id() == null ? other.getRegion_city_id() == null
						: this.getRegion_city_id().equals(other.getRegion_city_id()))
				&& (this.getRegion_cityname() == null ? other.getRegion_cityname() == null
						: this.getRegion_cityname().equals(other.getRegion_cityname()))
				&& (this.getRegion_id() == null ? other.getRegion_id() == null
						: this.getRegion_id().equals(other.getRegion_id()))
				&& (this.getRegion_name() == null ? other.getRegion_name() == null
						: this.getRegion_name().equals(other.getRegion_name()))
				&& (this.getDistrict() == null ? other.getDistrict() == null
						: this.getDistrict().equals(other.getDistrict()))
				&& (this.getFloor() == null ? other.getFloor() == null : this.getFloor().equals(other.getFloor()))
				&& (this.getTraffic_condition() == null ? other.getTraffic_condition() == null
						: this.getTraffic_condition().equals(other.getTraffic_condition()))
				&& (this.getActivate_time() == null ? other.getActivate_time() == null
						: this.getActivate_time().equals(other.getActivate_time()))
				&& (this.getProperty_fee() == null ? other.getProperty_fee() == null
						: this.getProperty_fee().equals(other.getProperty_fee()))
				&& (this.getParking_fee() == null ? other.getParking_fee() == null
						: this.getParking_fee().equals(other.getParking_fee()))
				&& (this.getConditioners_fee() == null ? other.getConditioners_fee() == null
						: this.getConditioners_fee().equals(other.getConditioners_fee()))
				&& (this.getIntro() == null ? other.getIntro() == null : this.getIntro().equals(other.getIntro()))
				&& (this.getCircum() == null ? other.getCircum() == null : this.getCircum().equals(other.getCircum()))
				&& (this.getLongitude() == null ? other.getLongitude() == null
						: this.getLongitude().equals(other.getLongitude()))
				&& (this.getLatitude() == null ? other.getLatitude() == null
						: this.getLatitude().equals(other.getLatitude()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getMansion_name() == null) ? 0 : getMansion_name().hashCode());
		result = prime * result + ((getMansion_picture() == null) ? 0 : getMansion_picture().hashCode());
		result = prime * result + ((getRegion_sh_id() == null) ? 0 : getRegion_sh_id().hashCode());
		result = prime * result + ((getRegion_shname() == null) ? 0 : getRegion_shname().hashCode());
		result = prime * result + ((getRegion_city_id() == null) ? 0 : getRegion_city_id().hashCode());
		result = prime * result + ((getRegion_cityname() == null) ? 0 : getRegion_cityname().hashCode());
		result = prime * result + ((getRegion_id() == null) ? 0 : getRegion_id().hashCode());
		result = prime * result + ((getRegion_name() == null) ? 0 : getRegion_name().hashCode());
		result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
		result = prime * result + ((getFloor() == null) ? 0 : getFloor().hashCode());
		result = prime * result + ((getTraffic_condition() == null) ? 0 : getTraffic_condition().hashCode());
		result = prime * result + ((getActivate_time() == null) ? 0 : getActivate_time().hashCode());
		result = prime * result + ((getProperty_fee() == null) ? 0 : getProperty_fee().hashCode());
		result = prime * result + ((getParking_fee() == null) ? 0 : getParking_fee().hashCode());
		result = prime * result + ((getConditioners_fee() == null) ? 0 : getConditioners_fee().hashCode());
		result = prime * result + ((getIntro() == null) ? 0 : getIntro().hashCode());
		result = prime * result + ((getCircum() == null) ? 0 : getCircum().hashCode());
		result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
		result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", mansion_name=").append(mansion_name);
		sb.append(", mansion_picture=").append(mansion_picture);
		sb.append(", region_sh_id=").append(region_sh_id);
		sb.append(", region_shname=").append(region_shname);
		sb.append(", region_city_id=").append(region_city_id);
		sb.append(", region_cityname=").append(region_cityname);
		sb.append(", region_id=").append(region_id);
		sb.append(", region_name=").append(region_name);
		sb.append(", district=").append(district);
		sb.append(", floor=").append(floor);
		sb.append(", traffic_condition=").append(traffic_condition);
		sb.append(", activate_time=").append(activate_time);
		sb.append(", property_fee=").append(property_fee);
		sb.append(", parking_fee=").append(parking_fee);
		sb.append(", conditioners_fee=").append(conditioners_fee);
		sb.append(", intro=").append(intro);
		sb.append(", circum=").append(circum);
		sb.append(", longitude=").append(longitude);
		sb.append(", latitude=").append(latitude);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}