package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Client implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client.phones
	 * @mbggenerated
	 */
	private Integer phones;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client.state_time
	 * @mbggenerated
	 */
	private Date state_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_client
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client.id
	 * @return  the value of t_client.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client.id
	 * @param id  the value for t_client.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client.phones
	 * @return  the value of t_client.phones
	 * @mbggenerated
	 */
	public Integer getPhones() {
		return phones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client.phones
	 * @param phones  the value for t_client.phones
	 * @mbggenerated
	 */
	public void setPhones(Integer phones) {
		this.phones = phones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client.state_time
	 * @return  the value of t_client.state_time
	 * @mbggenerated
	 */
	public Date getState_time() {
		return state_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client.state_time
	 * @param state_time  the value for t_client.state_time
	 * @mbggenerated
	 */
	public void setState_time(Date state_time) {
		this.state_time = state_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Client other = (Client) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getPhones() == null ? other.getPhones() == null : this.getPhones().equals(other.getPhones()))
				&& (this.getState_time() == null ? other.getState_time() == null
						: this.getState_time().equals(other.getState_time()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getPhones() == null) ? 0 : getPhones().hashCode());
		result = prime * result + ((getState_time() == null) ? 0 : getState_time().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", phones=").append(phones);
		sb.append(", state_time=").append(state_time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}