package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class DivideInto implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.design_name
	 * @mbggenerated
	 */
	private String design_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.transfer_con
	 * @mbggenerated
	 */
	private Byte transfer_con;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.transfer_lock
	 * @mbggenerated
	 */
	private Byte transfer_lock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.enter_per
	 * @mbggenerated
	 */
	private Integer enter_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.open_quot_per
	 * @mbggenerated
	 */
	private Integer open_quot_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.vindicate_per
	 * @mbggenerated
	 */
	private Integer vindicate_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.entrust_per
	 * @mbggenerated
	 */
	private Integer entrust_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.entrust_allot
	 * @mbggenerated
	 */
	private Byte entrust_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.take_key_per
	 * @mbggenerated
	 */
	private Integer take_key_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.take_key_allot
	 * @mbggenerated
	 */
	private Byte take_key_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.exclusive_per
	 * @mbggenerated
	 */
	private Integer exclusive_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.exclusive_allot
	 * @mbggenerated
	 */
	private Byte exclusive_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.send_photo_per
	 * @mbggenerated
	 */
	private Integer send_photo_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.send_photo_allot
	 * @mbggenerated
	 */
	private Byte send_photo_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.send_video_per
	 * @mbggenerated
	 */
	private Integer send_video_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.send_video_allot
	 * @mbggenerated
	 */
	private Byte send_video_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.bargain_per
	 * @mbggenerated
	 */
	private Integer bargain_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.bargain_allot
	 * @mbggenerated
	 */
	private Byte bargain_allot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.passenger_suorce_enter_per
	 * @mbggenerated
	 */
	private Integer passenger_suorce_enter_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.passenger_suorce_vindicate_per
	 * @mbggenerated
	 */
	private Integer passenger_suorce_vindicate_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.pact_clinch_per
	 * @mbggenerated
	 */
	private Integer pact_clinch_per;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_divide_into.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_divide_into
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.id
	 * @return  the value of t_divide_into.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.id
	 * @param id  the value for t_divide_into.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.design_name
	 * @return  the value of t_divide_into.design_name
	 * @mbggenerated
	 */
	public String getDesign_name() {
		return design_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.design_name
	 * @param design_name  the value for t_divide_into.design_name
	 * @mbggenerated
	 */
	public void setDesign_name(String design_name) {
		this.design_name = design_name == null ? null : design_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.status
	 * @return  the value of t_divide_into.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.status
	 * @param status  the value for t_divide_into.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.transfer_con
	 * @return  the value of t_divide_into.transfer_con
	 * @mbggenerated
	 */
	public Byte getTransfer_con() {
		return transfer_con;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.transfer_con
	 * @param transfer_con  the value for t_divide_into.transfer_con
	 * @mbggenerated
	 */
	public void setTransfer_con(Byte transfer_con) {
		this.transfer_con = transfer_con;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.transfer_lock
	 * @return  the value of t_divide_into.transfer_lock
	 * @mbggenerated
	 */
	public Byte getTransfer_lock() {
		return transfer_lock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.transfer_lock
	 * @param transfer_lock  the value for t_divide_into.transfer_lock
	 * @mbggenerated
	 */
	public void setTransfer_lock(Byte transfer_lock) {
		this.transfer_lock = transfer_lock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.enter_per
	 * @return  the value of t_divide_into.enter_per
	 * @mbggenerated
	 */
	public Integer getEnter_per() {
		return enter_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.enter_per
	 * @param enter_per  the value for t_divide_into.enter_per
	 * @mbggenerated
	 */
	public void setEnter_per(Integer enter_per) {
		this.enter_per = enter_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.open_quot_per
	 * @return  the value of t_divide_into.open_quot_per
	 * @mbggenerated
	 */
	public Integer getOpen_quot_per() {
		return open_quot_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.open_quot_per
	 * @param open_quot_per  the value for t_divide_into.open_quot_per
	 * @mbggenerated
	 */
	public void setOpen_quot_per(Integer open_quot_per) {
		this.open_quot_per = open_quot_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.vindicate_per
	 * @return  the value of t_divide_into.vindicate_per
	 * @mbggenerated
	 */
	public Integer getVindicate_per() {
		return vindicate_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.vindicate_per
	 * @param vindicate_per  the value for t_divide_into.vindicate_per
	 * @mbggenerated
	 */
	public void setVindicate_per(Integer vindicate_per) {
		this.vindicate_per = vindicate_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.entrust_per
	 * @return  the value of t_divide_into.entrust_per
	 * @mbggenerated
	 */
	public Integer getEntrust_per() {
		return entrust_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.entrust_per
	 * @param entrust_per  the value for t_divide_into.entrust_per
	 * @mbggenerated
	 */
	public void setEntrust_per(Integer entrust_per) {
		this.entrust_per = entrust_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.entrust_allot
	 * @return  the value of t_divide_into.entrust_allot
	 * @mbggenerated
	 */
	public Byte getEntrust_allot() {
		return entrust_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.entrust_allot
	 * @param entrust_allot  the value for t_divide_into.entrust_allot
	 * @mbggenerated
	 */
	public void setEntrust_allot(Byte entrust_allot) {
		this.entrust_allot = entrust_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.take_key_per
	 * @return  the value of t_divide_into.take_key_per
	 * @mbggenerated
	 */
	public Integer getTake_key_per() {
		return take_key_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.take_key_per
	 * @param take_key_per  the value for t_divide_into.take_key_per
	 * @mbggenerated
	 */
	public void setTake_key_per(Integer take_key_per) {
		this.take_key_per = take_key_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.take_key_allot
	 * @return  the value of t_divide_into.take_key_allot
	 * @mbggenerated
	 */
	public Byte getTake_key_allot() {
		return take_key_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.take_key_allot
	 * @param take_key_allot  the value for t_divide_into.take_key_allot
	 * @mbggenerated
	 */
	public void setTake_key_allot(Byte take_key_allot) {
		this.take_key_allot = take_key_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.exclusive_per
	 * @return  the value of t_divide_into.exclusive_per
	 * @mbggenerated
	 */
	public Integer getExclusive_per() {
		return exclusive_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.exclusive_per
	 * @param exclusive_per  the value for t_divide_into.exclusive_per
	 * @mbggenerated
	 */
	public void setExclusive_per(Integer exclusive_per) {
		this.exclusive_per = exclusive_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.exclusive_allot
	 * @return  the value of t_divide_into.exclusive_allot
	 * @mbggenerated
	 */
	public Byte getExclusive_allot() {
		return exclusive_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.exclusive_allot
	 * @param exclusive_allot  the value for t_divide_into.exclusive_allot
	 * @mbggenerated
	 */
	public void setExclusive_allot(Byte exclusive_allot) {
		this.exclusive_allot = exclusive_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.send_photo_per
	 * @return  the value of t_divide_into.send_photo_per
	 * @mbggenerated
	 */
	public Integer getSend_photo_per() {
		return send_photo_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.send_photo_per
	 * @param send_photo_per  the value for t_divide_into.send_photo_per
	 * @mbggenerated
	 */
	public void setSend_photo_per(Integer send_photo_per) {
		this.send_photo_per = send_photo_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.send_photo_allot
	 * @return  the value of t_divide_into.send_photo_allot
	 * @mbggenerated
	 */
	public Byte getSend_photo_allot() {
		return send_photo_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.send_photo_allot
	 * @param send_photo_allot  the value for t_divide_into.send_photo_allot
	 * @mbggenerated
	 */
	public void setSend_photo_allot(Byte send_photo_allot) {
		this.send_photo_allot = send_photo_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.send_video_per
	 * @return  the value of t_divide_into.send_video_per
	 * @mbggenerated
	 */
	public Integer getSend_video_per() {
		return send_video_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.send_video_per
	 * @param send_video_per  the value for t_divide_into.send_video_per
	 * @mbggenerated
	 */
	public void setSend_video_per(Integer send_video_per) {
		this.send_video_per = send_video_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.send_video_allot
	 * @return  the value of t_divide_into.send_video_allot
	 * @mbggenerated
	 */
	public Byte getSend_video_allot() {
		return send_video_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.send_video_allot
	 * @param send_video_allot  the value for t_divide_into.send_video_allot
	 * @mbggenerated
	 */
	public void setSend_video_allot(Byte send_video_allot) {
		this.send_video_allot = send_video_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.bargain_per
	 * @return  the value of t_divide_into.bargain_per
	 * @mbggenerated
	 */
	public Integer getBargain_per() {
		return bargain_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.bargain_per
	 * @param bargain_per  the value for t_divide_into.bargain_per
	 * @mbggenerated
	 */
	public void setBargain_per(Integer bargain_per) {
		this.bargain_per = bargain_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.bargain_allot
	 * @return  the value of t_divide_into.bargain_allot
	 * @mbggenerated
	 */
	public Byte getBargain_allot() {
		return bargain_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.bargain_allot
	 * @param bargain_allot  the value for t_divide_into.bargain_allot
	 * @mbggenerated
	 */
	public void setBargain_allot(Byte bargain_allot) {
		this.bargain_allot = bargain_allot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.passenger_suorce_enter_per
	 * @return  the value of t_divide_into.passenger_suorce_enter_per
	 * @mbggenerated
	 */
	public Integer getPassenger_suorce_enter_per() {
		return passenger_suorce_enter_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.passenger_suorce_enter_per
	 * @param passenger_suorce_enter_per  the value for t_divide_into.passenger_suorce_enter_per
	 * @mbggenerated
	 */
	public void setPassenger_suorce_enter_per(Integer passenger_suorce_enter_per) {
		this.passenger_suorce_enter_per = passenger_suorce_enter_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.passenger_suorce_vindicate_per
	 * @return  the value of t_divide_into.passenger_suorce_vindicate_per
	 * @mbggenerated
	 */
	public Integer getPassenger_suorce_vindicate_per() {
		return passenger_suorce_vindicate_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.passenger_suorce_vindicate_per
	 * @param passenger_suorce_vindicate_per  the value for t_divide_into.passenger_suorce_vindicate_per
	 * @mbggenerated
	 */
	public void setPassenger_suorce_vindicate_per(Integer passenger_suorce_vindicate_per) {
		this.passenger_suorce_vindicate_per = passenger_suorce_vindicate_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.pact_clinch_per
	 * @return  the value of t_divide_into.pact_clinch_per
	 * @mbggenerated
	 */
	public Integer getPact_clinch_per() {
		return pact_clinch_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.pact_clinch_per
	 * @param pact_clinch_per  the value for t_divide_into.pact_clinch_per
	 * @mbggenerated
	 */
	public void setPact_clinch_per(Integer pact_clinch_per) {
		this.pact_clinch_per = pact_clinch_per;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_divide_into.time
	 * @return  the value of t_divide_into.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_divide_into.time
	 * @param time  the value for t_divide_into.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_divide_into
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DivideInto other = (DivideInto) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDesign_name() == null ? other.getDesign_name() == null
						: this.getDesign_name().equals(other.getDesign_name()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getTransfer_con() == null ? other.getTransfer_con() == null
						: this.getTransfer_con().equals(other.getTransfer_con()))
				&& (this.getTransfer_lock() == null ? other.getTransfer_lock() == null
						: this.getTransfer_lock().equals(other.getTransfer_lock()))
				&& (this.getEnter_per() == null ? other.getEnter_per() == null
						: this.getEnter_per().equals(other.getEnter_per()))
				&& (this.getOpen_quot_per() == null ? other.getOpen_quot_per() == null
						: this.getOpen_quot_per().equals(other.getOpen_quot_per()))
				&& (this.getVindicate_per() == null ? other.getVindicate_per() == null
						: this.getVindicate_per().equals(other.getVindicate_per()))
				&& (this.getEntrust_per() == null ? other.getEntrust_per() == null
						: this.getEntrust_per().equals(other.getEntrust_per()))
				&& (this.getEntrust_allot() == null ? other.getEntrust_allot() == null
						: this.getEntrust_allot().equals(other.getEntrust_allot()))
				&& (this.getTake_key_per() == null ? other.getTake_key_per() == null
						: this.getTake_key_per().equals(other.getTake_key_per()))
				&& (this.getTake_key_allot() == null ? other.getTake_key_allot() == null
						: this.getTake_key_allot().equals(other.getTake_key_allot()))
				&& (this.getExclusive_per() == null ? other.getExclusive_per() == null
						: this.getExclusive_per().equals(other.getExclusive_per()))
				&& (this.getExclusive_allot() == null ? other.getExclusive_allot() == null
						: this.getExclusive_allot().equals(other.getExclusive_allot()))
				&& (this.getSend_photo_per() == null ? other.getSend_photo_per() == null
						: this.getSend_photo_per().equals(other.getSend_photo_per()))
				&& (this.getSend_photo_allot() == null ? other.getSend_photo_allot() == null
						: this.getSend_photo_allot().equals(other.getSend_photo_allot()))
				&& (this.getSend_video_per() == null ? other.getSend_video_per() == null
						: this.getSend_video_per().equals(other.getSend_video_per()))
				&& (this.getSend_video_allot() == null ? other.getSend_video_allot() == null
						: this.getSend_video_allot().equals(other.getSend_video_allot()))
				&& (this.getBargain_per() == null ? other.getBargain_per() == null
						: this.getBargain_per().equals(other.getBargain_per()))
				&& (this.getBargain_allot() == null ? other.getBargain_allot() == null
						: this.getBargain_allot().equals(other.getBargain_allot()))
				&& (this.getPassenger_suorce_enter_per() == null ? other.getPassenger_suorce_enter_per() == null
						: this.getPassenger_suorce_enter_per().equals(other.getPassenger_suorce_enter_per()))
				&& (this.getPassenger_suorce_vindicate_per() == null ? other.getPassenger_suorce_vindicate_per() == null
						: this.getPassenger_suorce_vindicate_per().equals(other.getPassenger_suorce_vindicate_per()))
				&& (this.getPact_clinch_per() == null ? other.getPact_clinch_per() == null
						: this.getPact_clinch_per().equals(other.getPact_clinch_per()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_divide_into
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDesign_name() == null) ? 0 : getDesign_name().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getTransfer_con() == null) ? 0 : getTransfer_con().hashCode());
		result = prime * result + ((getTransfer_lock() == null) ? 0 : getTransfer_lock().hashCode());
		result = prime * result + ((getEnter_per() == null) ? 0 : getEnter_per().hashCode());
		result = prime * result + ((getOpen_quot_per() == null) ? 0 : getOpen_quot_per().hashCode());
		result = prime * result + ((getVindicate_per() == null) ? 0 : getVindicate_per().hashCode());
		result = prime * result + ((getEntrust_per() == null) ? 0 : getEntrust_per().hashCode());
		result = prime * result + ((getEntrust_allot() == null) ? 0 : getEntrust_allot().hashCode());
		result = prime * result + ((getTake_key_per() == null) ? 0 : getTake_key_per().hashCode());
		result = prime * result + ((getTake_key_allot() == null) ? 0 : getTake_key_allot().hashCode());
		result = prime * result + ((getExclusive_per() == null) ? 0 : getExclusive_per().hashCode());
		result = prime * result + ((getExclusive_allot() == null) ? 0 : getExclusive_allot().hashCode());
		result = prime * result + ((getSend_photo_per() == null) ? 0 : getSend_photo_per().hashCode());
		result = prime * result + ((getSend_photo_allot() == null) ? 0 : getSend_photo_allot().hashCode());
		result = prime * result + ((getSend_video_per() == null) ? 0 : getSend_video_per().hashCode());
		result = prime * result + ((getSend_video_allot() == null) ? 0 : getSend_video_allot().hashCode());
		result = prime * result + ((getBargain_per() == null) ? 0 : getBargain_per().hashCode());
		result = prime * result + ((getBargain_allot() == null) ? 0 : getBargain_allot().hashCode());
		result = prime * result
				+ ((getPassenger_suorce_enter_per() == null) ? 0 : getPassenger_suorce_enter_per().hashCode());
		result = prime * result
				+ ((getPassenger_suorce_vindicate_per() == null) ? 0 : getPassenger_suorce_vindicate_per().hashCode());
		result = prime * result + ((getPact_clinch_per() == null) ? 0 : getPact_clinch_per().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_divide_into
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", design_name=").append(design_name);
		sb.append(", status=").append(status);
		sb.append(", transfer_con=").append(transfer_con);
		sb.append(", transfer_lock=").append(transfer_lock);
		sb.append(", enter_per=").append(enter_per);
		sb.append(", open_quot_per=").append(open_quot_per);
		sb.append(", vindicate_per=").append(vindicate_per);
		sb.append(", entrust_per=").append(entrust_per);
		sb.append(", entrust_allot=").append(entrust_allot);
		sb.append(", take_key_per=").append(take_key_per);
		sb.append(", take_key_allot=").append(take_key_allot);
		sb.append(", exclusive_per=").append(exclusive_per);
		sb.append(", exclusive_allot=").append(exclusive_allot);
		sb.append(", send_photo_per=").append(send_photo_per);
		sb.append(", send_photo_allot=").append(send_photo_allot);
		sb.append(", send_video_per=").append(send_video_per);
		sb.append(", send_video_allot=").append(send_video_allot);
		sb.append(", bargain_per=").append(bargain_per);
		sb.append(", bargain_allot=").append(bargain_allot);
		sb.append(", passenger_suorce_enter_per=").append(passenger_suorce_enter_per);
		sb.append(", passenger_suorce_vindicate_per=").append(passenger_suorce_vindicate_per);
		sb.append(", pact_clinch_per=").append(pact_clinch_per);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}