package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Entrustsee implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.broker_id
	 * @mbggenerated
	 */
	private Long broker_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.seetype
	 * @mbggenerated
	 */
	private Integer seetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.pleasetime
	 * @mbggenerated
	 */
	private Date pleasetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.phone_number
	 * @mbggenerated
	 */
	private Long phone_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_entrustsee.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.id
	 * @return  the value of t_entrustsee.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.id
	 * @param id  the value for t_entrustsee.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.broker_id
	 * @return  the value of t_entrustsee.broker_id
	 * @mbggenerated
	 */
	public Long getBroker_id() {
		return broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.broker_id
	 * @param broker_id  the value for t_entrustsee.broker_id
	 * @mbggenerated
	 */
	public void setBroker_id(Long broker_id) {
		this.broker_id = broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.seetype
	 * @return  the value of t_entrustsee.seetype
	 * @mbggenerated
	 */
	public Integer getSeetype() {
		return seetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.seetype
	 * @param seetype  the value for t_entrustsee.seetype
	 * @mbggenerated
	 */
	public void setSeetype(Integer seetype) {
		this.seetype = seetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.pleasetime
	 * @return  the value of t_entrustsee.pleasetime
	 * @mbggenerated
	 */
	public Date getPleasetime() {
		return pleasetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.pleasetime
	 * @param pleasetime  the value for t_entrustsee.pleasetime
	 * @mbggenerated
	 */
	public void setPleasetime(Date pleasetime) {
		this.pleasetime = pleasetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.phone_number
	 * @return  the value of t_entrustsee.phone_number
	 * @mbggenerated
	 */
	public Long getPhone_number() {
		return phone_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.phone_number
	 * @param phone_number  the value for t_entrustsee.phone_number
	 * @mbggenerated
	 */
	public void setPhone_number(Long phone_number) {
		this.phone_number = phone_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.houses_new_id
	 * @return  the value of t_entrustsee.houses_new_id
	 * @mbggenerated
	 */
	public Long getHouses_new_id() {
		return houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.houses_new_id
	 * @param houses_new_id  the value for t_entrustsee.houses_new_id
	 * @mbggenerated
	 */
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_entrustsee.type
	 * @return  the value of t_entrustsee.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_entrustsee.type
	 * @param type  the value for t_entrustsee.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Entrustsee other = (Entrustsee) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getBroker_id() == null ? other.getBroker_id() == null
						: this.getBroker_id().equals(other.getBroker_id()))
				&& (this.getSeetype() == null ? other.getSeetype() == null
						: this.getSeetype().equals(other.getSeetype()))
				&& (this.getPleasetime() == null ? other.getPleasetime() == null
						: this.getPleasetime().equals(other.getPleasetime()))
				&& (this.getPhone_number() == null ? other.getPhone_number() == null
						: this.getPhone_number().equals(other.getPhone_number()))
				&& (this.getHouses_new_id() == null ? other.getHouses_new_id() == null
						: this.getHouses_new_id().equals(other.getHouses_new_id()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getBroker_id() == null) ? 0 : getBroker_id().hashCode());
		result = prime * result + ((getSeetype() == null) ? 0 : getSeetype().hashCode());
		result = prime * result + ((getPleasetime() == null) ? 0 : getPleasetime().hashCode());
		result = prime * result + ((getPhone_number() == null) ? 0 : getPhone_number().hashCode());
		result = prime * result + ((getHouses_new_id() == null) ? 0 : getHouses_new_id().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", broker_id=").append(broker_id);
		sb.append(", seetype=").append(seetype);
		sb.append(", pleasetime=").append(pleasetime);
		sb.append(", phone_number=").append(phone_number);
		sb.append(", houses_new_id=").append(houses_new_id);
		sb.append(", type=").append(type);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}