package com.yqwl.pojo;

import java.io.Serializable;

public class Existing implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_existing.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_existing.province_id
     *
     * @mbggenerated
     */
    private Integer province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_existing.province_name
     *
     * @mbggenerated
     */
    private String province_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_existing.city_id
     *
     * @mbggenerated
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_existing.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_existing.id
     *
     * @return the value of t_existing.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_existing.id
     *
     * @param id the value for t_existing.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_existing.province_id
     *
     * @return the value of t_existing.province_id
     *
     * @mbggenerated
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_existing.province_id
     *
     * @param province_id the value for t_existing.province_id
     *
     * @mbggenerated
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_existing.province_name
     *
     * @return the value of t_existing.province_name
     *
     * @mbggenerated
     */
    public String getProvince_name() {
        return province_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_existing.province_name
     *
     * @param province_name the value for t_existing.province_name
     *
     * @mbggenerated
     */
    public void setProvince_name(String province_name) {
        this.province_name = province_name == null ? null : province_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_existing.city_id
     *
     * @return the value of t_existing.city_id
     *
     * @mbggenerated
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_existing.city_id
     *
     * @param city_id the value for t_existing.city_id
     *
     * @mbggenerated
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_existing.city
     *
     * @return the value of t_existing.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_existing.city
     *
     * @param city the value for t_existing.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Existing other = (Existing) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProvince_id() == null ? other.getProvince_id() == null : this.getProvince_id().equals(other.getProvince_id()))
            && (this.getProvince_name() == null ? other.getProvince_name() == null : this.getProvince_name().equals(other.getProvince_name()))
            && (this.getCity_id() == null ? other.getCity_id() == null : this.getCity_id().equals(other.getCity_id()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProvince_id() == null) ? 0 : getProvince_id().hashCode());
        result = prime * result + ((getProvince_name() == null) ? 0 : getProvince_name().hashCode());
        result = prime * result + ((getCity_id() == null) ? 0 : getCity_id().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", province_id=").append(province_id);
        sb.append(", province_name=").append(province_name);
        sb.append(", city_id=").append(city_id);
        sb.append(", city=").append(city);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}