package com.yqwl.pojo;

import java.io.Serializable;

public class FuncRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_func_role.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_func_role.role_id
     *
     * @mbggenerated
     */
    private Long role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_func_role.function_id
     *
     * @mbggenerated
     */
    private Long function_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_func_role.id
     *
     * @return the value of t_func_role.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_func_role.id
     *
     * @param id the value for t_func_role.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_func_role.role_id
     *
     * @return the value of t_func_role.role_id
     *
     * @mbggenerated
     */
    public Long getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_func_role.role_id
     *
     * @param role_id the value for t_func_role.role_id
     *
     * @mbggenerated
     */
    public void setRole_id(Long role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_func_role.function_id
     *
     * @return the value of t_func_role.function_id
     *
     * @mbggenerated
     */
    public Long getFunction_id() {
        return function_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_func_role.function_id
     *
     * @param function_id the value for t_func_role.function_id
     *
     * @mbggenerated
     */
    public void setFunction_id(Long function_id) {
        this.function_id = function_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FuncRole other = (FuncRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRole_id() == null ? other.getRole_id() == null : this.getRole_id().equals(other.getRole_id()))
            && (this.getFunction_id() == null ? other.getFunction_id() == null : this.getFunction_id().equals(other.getFunction_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRole_id() == null) ? 0 : getRole_id().hashCode());
        result = prime * result + ((getFunction_id() == null) ? 0 : getFunction_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", role_id=").append(role_id);
        sb.append(", function_id=").append(function_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}