package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class HomePageRecommended implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.city_id
	 * @mbggenerated
	 */
	private Integer city_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.building_id
	 * @mbggenerated
	 */
	private Long building_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.introduce
	 * @mbggenerated
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.img
	 * @mbggenerated
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_home_page_recommended.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.id
	 * @return  the value of t_home_page_recommended.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.id
	 * @param id  the value for t_home_page_recommended.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.city_id
	 * @return  the value of t_home_page_recommended.city_id
	 * @mbggenerated
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.city_id
	 * @param city_id  the value for t_home_page_recommended.city_id
	 * @mbggenerated
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.name
	 * @return  the value of t_home_page_recommended.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.name
	 * @param name  the value for t_home_page_recommended.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.building_id
	 * @return  the value of t_home_page_recommended.building_id
	 * @mbggenerated
	 */
	public Long getBuilding_id() {
		return building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.building_id
	 * @param building_id  the value for t_home_page_recommended.building_id
	 * @mbggenerated
	 */
	public void setBuilding_id(Long building_id) {
		this.building_id = building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.introduce
	 * @return  the value of t_home_page_recommended.introduce
	 * @mbggenerated
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.introduce
	 * @param introduce  the value for t_home_page_recommended.introduce
	 * @mbggenerated
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce == null ? null : introduce.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.img
	 * @return  the value of t_home_page_recommended.img
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.img
	 * @param img  the value for t_home_page_recommended.img
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.type
	 * @return  the value of t_home_page_recommended.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.type
	 * @param type  the value for t_home_page_recommended.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_home_page_recommended.time
	 * @return  the value of t_home_page_recommended.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_home_page_recommended.time
	 * @param time  the value for t_home_page_recommended.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		HomePageRecommended other = (HomePageRecommended) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getCity_id() == null ? other.getCity_id() == null
						: this.getCity_id().equals(other.getCity_id()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getBuilding_id() == null ? other.getBuilding_id() == null
						: this.getBuilding_id().equals(other.getBuilding_id()))
				&& (this.getIntroduce() == null ? other.getIntroduce() == null
						: this.getIntroduce().equals(other.getIntroduce()))
				&& (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getCity_id() == null) ? 0 : getCity_id().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getBuilding_id() == null) ? 0 : getBuilding_id().hashCode());
		result = prime * result + ((getIntroduce() == null) ? 0 : getIntroduce().hashCode());
		result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", city_id=").append(city_id);
		sb.append(", name=").append(name);
		sb.append(", building_id=").append(building_id);
		sb.append(", introduce=").append(introduce);
		sb.append(", img=").append(img);
		sb.append(", type=").append(type);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}