package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Launch implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.city_id
	 * @mbggenerated
	 */
	private Long city_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.city_name
	 * @mbggenerated
	 */
	private String city_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.areas_id
	 * @mbggenerated
	 */
	private Long areas_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.areas_name
	 * @mbggenerated
	 */
	private String areas_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.detail
	 * @mbggenerated
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.expect_price
	 * @mbggenerated
	 */
	private Long expect_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.price_unit
	 * @mbggenerated
	 */
	private Integer price_unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.office
	 * @mbggenerated
	 */
	private Long office;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.user_names
	 * @mbggenerated
	 */
	private String user_names;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.user_number
	 * @mbggenerated
	 */
	private Long user_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.times
	 * @mbggenerated
	 */
	private Date times;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_launch.houses_name
	 * @mbggenerated
	 */
	private byte[] houses_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_launch
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.id
	 * @return  the value of t_launch.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.id
	 * @param id  the value for t_launch.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.city_id
	 * @return  the value of t_launch.city_id
	 * @mbggenerated
	 */
	public Long getCity_id() {
		return city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.city_id
	 * @param city_id  the value for t_launch.city_id
	 * @mbggenerated
	 */
	public void setCity_id(Long city_id) {
		this.city_id = city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.city_name
	 * @return  the value of t_launch.city_name
	 * @mbggenerated
	 */
	public String getCity_name() {
		return city_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.city_name
	 * @param city_name  the value for t_launch.city_name
	 * @mbggenerated
	 */
	public void setCity_name(String city_name) {
		this.city_name = city_name == null ? null : city_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.areas_id
	 * @return  the value of t_launch.areas_id
	 * @mbggenerated
	 */
	public Long getAreas_id() {
		return areas_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.areas_id
	 * @param areas_id  the value for t_launch.areas_id
	 * @mbggenerated
	 */
	public void setAreas_id(Long areas_id) {
		this.areas_id = areas_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.areas_name
	 * @return  the value of t_launch.areas_name
	 * @mbggenerated
	 */
	public String getAreas_name() {
		return areas_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.areas_name
	 * @param areas_name  the value for t_launch.areas_name
	 * @mbggenerated
	 */
	public void setAreas_name(String areas_name) {
		this.areas_name = areas_name == null ? null : areas_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.detail
	 * @return  the value of t_launch.detail
	 * @mbggenerated
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.detail
	 * @param detail  the value for t_launch.detail
	 * @mbggenerated
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.expect_price
	 * @return  the value of t_launch.expect_price
	 * @mbggenerated
	 */
	public Long getExpect_price() {
		return expect_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.expect_price
	 * @param expect_price  the value for t_launch.expect_price
	 * @mbggenerated
	 */
	public void setExpect_price(Long expect_price) {
		this.expect_price = expect_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.price_unit
	 * @return  the value of t_launch.price_unit
	 * @mbggenerated
	 */
	public Integer getPrice_unit() {
		return price_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.price_unit
	 * @param price_unit  the value for t_launch.price_unit
	 * @mbggenerated
	 */
	public void setPrice_unit(Integer price_unit) {
		this.price_unit = price_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.office
	 * @return  the value of t_launch.office
	 * @mbggenerated
	 */
	public Long getOffice() {
		return office;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.office
	 * @param office  the value for t_launch.office
	 * @mbggenerated
	 */
	public void setOffice(Long office) {
		this.office = office;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.user_names
	 * @return  the value of t_launch.user_names
	 * @mbggenerated
	 */
	public String getUser_names() {
		return user_names;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.user_names
	 * @param user_names  the value for t_launch.user_names
	 * @mbggenerated
	 */
	public void setUser_names(String user_names) {
		this.user_names = user_names == null ? null : user_names.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.user_number
	 * @return  the value of t_launch.user_number
	 * @mbggenerated
	 */
	public Long getUser_number() {
		return user_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.user_number
	 * @param user_number  the value for t_launch.user_number
	 * @mbggenerated
	 */
	public void setUser_number(Long user_number) {
		this.user_number = user_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.times
	 * @return  the value of t_launch.times
	 * @mbggenerated
	 */
	public Date getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.times
	 * @param times  the value for t_launch.times
	 * @mbggenerated
	 */
	public void setTimes(Date times) {
		this.times = times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_launch.houses_name
	 * @return  the value of t_launch.houses_name
	 * @mbggenerated
	 */
	public byte[] getHouses_name() {
		return houses_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_launch.houses_name
	 * @param houses_name  the value for t_launch.houses_name
	 * @mbggenerated
	 */
	public void setHouses_name(byte[] houses_name) {
		this.houses_name = houses_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_launch
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Launch other = (Launch) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getCity_id() == null ? other.getCity_id() == null
						: this.getCity_id().equals(other.getCity_id()))
				&& (this.getCity_name() == null ? other.getCity_name() == null
						: this.getCity_name().equals(other.getCity_name()))
				&& (this.getAreas_id() == null ? other.getAreas_id() == null
						: this.getAreas_id().equals(other.getAreas_id()))
				&& (this.getAreas_name() == null ? other.getAreas_name() == null
						: this.getAreas_name().equals(other.getAreas_name()))
				&& (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
				&& (this.getExpect_price() == null ? other.getExpect_price() == null
						: this.getExpect_price().equals(other.getExpect_price()))
				&& (this.getPrice_unit() == null ? other.getPrice_unit() == null
						: this.getPrice_unit().equals(other.getPrice_unit()))
				&& (this.getOffice() == null ? other.getOffice() == null : this.getOffice().equals(other.getOffice()))
				&& (this.getUser_names() == null ? other.getUser_names() == null
						: this.getUser_names().equals(other.getUser_names()))
				&& (this.getUser_number() == null ? other.getUser_number() == null
						: this.getUser_number().equals(other.getUser_number()))
				&& (this.getTimes() == null ? other.getTimes() == null : this.getTimes().equals(other.getTimes()))
				&& (this.getHouses_name() == null ? other.getHouses_name() == null
						: this.getHouses_name().equals(other.getHouses_name()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_launch
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getCity_id() == null) ? 0 : getCity_id().hashCode());
		result = prime * result + ((getCity_name() == null) ? 0 : getCity_name().hashCode());
		result = prime * result + ((getAreas_id() == null) ? 0 : getAreas_id().hashCode());
		result = prime * result + ((getAreas_name() == null) ? 0 : getAreas_name().hashCode());
		result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
		result = prime * result + ((getExpect_price() == null) ? 0 : getExpect_price().hashCode());
		result = prime * result + ((getPrice_unit() == null) ? 0 : getPrice_unit().hashCode());
		result = prime * result + ((getOffice() == null) ? 0 : getOffice().hashCode());
		result = prime * result + ((getUser_names() == null) ? 0 : getUser_names().hashCode());
		result = prime * result + ((getUser_number() == null) ? 0 : getUser_number().hashCode());
		result = prime * result + ((getTimes() == null) ? 0 : getTimes().hashCode());
		result = prime * result + ((getHouses_name() == null) ? 0 : getHouses_name().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_launch
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", city_id=").append(city_id);
		sb.append(", city_name=").append(city_name);
		sb.append(", areas_id=").append(areas_id);
		sb.append(", areas_name=").append(areas_name);
		sb.append(", detail=").append(detail);
		sb.append(", expect_price=").append(expect_price);
		sb.append(", price_unit=").append(price_unit);
		sb.append(", office=").append(office);
		sb.append(", user_names=").append(user_names);
		sb.append(", user_number=").append(user_number);
		sb.append(", times=").append(times);
		sb.append(", houses_name=").append(houses_name);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}