package com.yqwl.pojo;

import java.io.Serializable;

public class Leaser implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.names
	 * @mbggenerated
	 */
	private String names;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.phone
	 * @mbggenerated
	 */
	private Long phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leaser.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.id
	 * @return  the value of t_leaser.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.id
	 * @param id  the value for t_leaser.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.names
	 * @return  the value of t_leaser.names
	 * @mbggenerated
	 */
	public String getNames() {
		return names;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.names
	 * @param names  the value for t_leaser.names
	 * @mbggenerated
	 */
	public void setNames(String names) {
		this.names = names == null ? null : names.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.phone
	 * @return  the value of t_leaser.phone
	 * @mbggenerated
	 */
	public Long getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.phone
	 * @param phone  the value for t_leaser.phone
	 * @mbggenerated
	 */
	public void setPhone(Long phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.houses_new_id
	 * @return  the value of t_leaser.houses_new_id
	 * @mbggenerated
	 */
	public Long getHouses_new_id() {
		return houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.houses_new_id
	 * @param houses_new_id  the value for t_leaser.houses_new_id
	 * @mbggenerated
	 */
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.remark
	 * @return  the value of t_leaser.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.remark
	 * @param remark  the value for t_leaser.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leaser.type
	 * @return  the value of t_leaser.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leaser.type
	 * @param type  the value for t_leaser.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Leaser other = (Leaser) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getNames() == null ? other.getNames() == null : this.getNames().equals(other.getNames()))
				&& (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
				&& (this.getHouses_new_id() == null ? other.getHouses_new_id() == null
						: this.getHouses_new_id().equals(other.getHouses_new_id()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getNames() == null) ? 0 : getNames().hashCode());
		result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
		result = prime * result + ((getHouses_new_id() == null) ? 0 : getHouses_new_id().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", names=").append(names);
		sb.append(", phone=").append(phone);
		sb.append(", houses_new_id=").append(houses_new_id);
		sb.append(", remark=").append(remark);
		sb.append(", type=").append(type);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}