package com.yqwl.pojo;

import java.io.Serializable;

public class NewsPic implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_pic.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_pic.journalism_id
	 * @mbggenerated
	 */
	private Long journalism_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_pic.picture
	 * @mbggenerated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_pic.id
	 * @return  the value of t_news_pic.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_pic.id
	 * @param id  the value for t_news_pic.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_pic.journalism_id
	 * @return  the value of t_news_pic.journalism_id
	 * @mbggenerated
	 */
	public Long getJournalism_id() {
		return journalism_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_pic.journalism_id
	 * @param journalism_id  the value for t_news_pic.journalism_id
	 * @mbggenerated
	 */
	public void setJournalism_id(Long journalism_id) {
		this.journalism_id = journalism_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_pic.picture
	 * @return  the value of t_news_pic.picture
	 * @mbggenerated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_pic.picture
	 * @param picture  the value for t_news_pic.picture
	 * @mbggenerated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		NewsPic other = (NewsPic) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getJournalism_id() == null ? other.getJournalism_id() == null
						: this.getJournalism_id().equals(other.getJournalism_id()))
				&& (this.getPicture() == null ? other.getPicture() == null
						: this.getPicture().equals(other.getPicture()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getJournalism_id() == null) ? 0 : getJournalism_id().hashCode());
		result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", journalism_id=").append(journalism_id);
		sb.append(", picture=").append(picture);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}