package com.yqwl.pojo;

import java.io.Serializable;

public class Photo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_photo.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_photo.building_id
	 * @mbggenerated
	 */
	private Long building_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_photo.photo
	 * @mbggenerated
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_photo
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_photo.id
	 * @return  the value of t_photo.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_photo.id
	 * @param id  the value for t_photo.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_photo.building_id
	 * @return  the value of t_photo.building_id
	 * @mbggenerated
	 */
	public Long getBuilding_id() {
		return building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_photo.building_id
	 * @param building_id  the value for t_photo.building_id
	 * @mbggenerated
	 */
	public void setBuilding_id(Long building_id) {
		this.building_id = building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_photo.photo
	 * @return  the value of t_photo.photo
	 * @mbggenerated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_photo.photo
	 * @param photo  the value for t_photo.photo
	 * @mbggenerated
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Photo other = (Photo) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getBuilding_id() == null ? other.getBuilding_id() == null
						: this.getBuilding_id().equals(other.getBuilding_id()))
				&& (this.getPhoto() == null ? other.getPhoto() == null : this.getPhoto().equals(other.getPhoto()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getBuilding_id() == null) ? 0 : getBuilding_id().hashCode());
		result = prime * result + ((getPhoto() == null) ? 0 : getPhoto().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", building_id=").append(building_id);
		sb.append(", photo=").append(photo);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}