package com.yqwl.pojo;

import java.io.Serializable;

public class Picture implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.houses_new_id
	 * @mbggenerated
	 */
	private Long houses_new_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.broker_id
	 * @mbggenerated
	 */
	private Long broker_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.picture
	 * @mbggenerated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_picture
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.id
	 * @return  the value of t_picture.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.id
	 * @param id  the value for t_picture.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.houses_new_id
	 * @return  the value of t_picture.houses_new_id
	 * @mbggenerated
	 */
	public Long getHouses_new_id() {
		return houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.houses_new_id
	 * @param houses_new_id  the value for t_picture.houses_new_id
	 * @mbggenerated
	 */
	public void setHouses_new_id(Long houses_new_id) {
		this.houses_new_id = houses_new_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.broker_id
	 * @return  the value of t_picture.broker_id
	 * @mbggenerated
	 */
	public Long getBroker_id() {
		return broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.broker_id
	 * @param broker_id  the value for t_picture.broker_id
	 * @mbggenerated
	 */
	public void setBroker_id(Long broker_id) {
		this.broker_id = broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.picture
	 * @return  the value of t_picture.picture
	 * @mbggenerated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.picture
	 * @param picture  the value for t_picture.picture
	 * @mbggenerated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Picture other = (Picture) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getHouses_new_id() == null ? other.getHouses_new_id() == null
						: this.getHouses_new_id().equals(other.getHouses_new_id()))
				&& (this.getBroker_id() == null ? other.getBroker_id() == null
						: this.getBroker_id().equals(other.getBroker_id()))
				&& (this.getPicture() == null ? other.getPicture() == null
						: this.getPicture().equals(other.getPicture()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getHouses_new_id() == null) ? 0 : getHouses_new_id().hashCode());
		result = prime * result + ((getBroker_id() == null) ? 0 : getBroker_id().hashCode());
		result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", houses_new_id=").append(houses_new_id);
		sb.append(", broker_id=").append(broker_id);
		sb.append(", picture=").append(picture);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}