package com.yqwl.pojo;

import java.io.Serializable;

public class Region implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.area_id
	 * @mbggenerated
	 */
	private Integer area_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.pid
	 * @mbggenerated
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.sort
	 * @mbggenerated
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_region
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.area_id
	 * @return  the value of t_region.area_id
	 * @mbggenerated
	 */
	public Integer getArea_id() {
		return area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.area_id
	 * @param area_id  the value for t_region.area_id
	 * @mbggenerated
	 */
	public void setArea_id(Integer area_id) {
		this.area_id = area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.title
	 * @return  the value of t_region.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.title
	 * @param title  the value for t_region.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.pid
	 * @return  the value of t_region.pid
	 * @mbggenerated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.pid
	 * @param pid  the value for t_region.pid
	 * @mbggenerated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.sort
	 * @return  the value of t_region.sort
	 * @mbggenerated
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.sort
	 * @param sort  the value for t_region.sort
	 * @mbggenerated
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Region other = (Region) that;
		return (this.getArea_id() == null ? other.getArea_id() == null : this.getArea_id().equals(other.getArea_id()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
				&& (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getArea_id() == null) ? 0 : getArea_id().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
		result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", area_id=").append(area_id);
		sb.append(", title=").append(title);
		sb.append(", pid=").append(pid);
		sb.append(", sort=").append(sort);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}