package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class SucceedDeal implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.house_id
	 * @mbggenerated
	 */
	private Long house_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.succeed_time
	 * @mbggenerated
	 */
	private Date succeed_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.rent_start_time
	 * @mbggenerated
	 */
	private Date rent_start_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.rent_end_time
	 * @mbggenerated
	 */
	private Date rent_end_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.broker_id
	 * @mbggenerated
	 */
	private Long broker_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.pack_no
	 * @mbggenerated
	 */
	private String pack_no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.rental
	 * @mbggenerated
	 */
	private Integer rental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.brokerage
	 * @mbggenerated
	 */
	private Integer brokerage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.land_certificate
	 * @mbggenerated
	 */
	private String land_certificate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.certificate_of_title
	 * @mbggenerated
	 */
	private String certificate_of_title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.supplement
	 * @mbggenerated
	 */
	private String supplement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_a_phone
	 * @mbggenerated
	 */
	private String party_a_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_a_name
	 * @mbggenerated
	 */
	private String party_a_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_a_sex
	 * @mbggenerated
	 */
	private Integer party_a_sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_a_id_number
	 * @mbggenerated
	 */
	private String party_a_id_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_a_address
	 * @mbggenerated
	 */
	private String party_a_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_b_user_id
	 * @mbggenerated
	 */
	private Long party_b_user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_b_sex
	 * @mbggenerated
	 */
	private Integer party_b_sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succeed_deal.party_b_id_number
	 * @mbggenerated
	 */
	private String party_b_id_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_succeed_deal
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.id
	 * @return  the value of t_succeed_deal.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.id
	 * @param id  the value for t_succeed_deal.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.house_id
	 * @return  the value of t_succeed_deal.house_id
	 * @mbggenerated
	 */
	public Long getHouse_id() {
		return house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.house_id
	 * @param house_id  the value for t_succeed_deal.house_id
	 * @mbggenerated
	 */
	public void setHouse_id(Long house_id) {
		this.house_id = house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.succeed_time
	 * @return  the value of t_succeed_deal.succeed_time
	 * @mbggenerated
	 */
	public Date getSucceed_time() {
		return succeed_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.succeed_time
	 * @param succeed_time  the value for t_succeed_deal.succeed_time
	 * @mbggenerated
	 */
	public void setSucceed_time(Date succeed_time) {
		this.succeed_time = succeed_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.rent_start_time
	 * @return  the value of t_succeed_deal.rent_start_time
	 * @mbggenerated
	 */
	public Date getRent_start_time() {
		return rent_start_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.rent_start_time
	 * @param rent_start_time  the value for t_succeed_deal.rent_start_time
	 * @mbggenerated
	 */
	public void setRent_start_time(Date rent_start_time) {
		this.rent_start_time = rent_start_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.rent_end_time
	 * @return  the value of t_succeed_deal.rent_end_time
	 * @mbggenerated
	 */
	public Date getRent_end_time() {
		return rent_end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.rent_end_time
	 * @param rent_end_time  the value for t_succeed_deal.rent_end_time
	 * @mbggenerated
	 */
	public void setRent_end_time(Date rent_end_time) {
		this.rent_end_time = rent_end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.broker_id
	 * @return  the value of t_succeed_deal.broker_id
	 * @mbggenerated
	 */
	public Long getBroker_id() {
		return broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.broker_id
	 * @param broker_id  the value for t_succeed_deal.broker_id
	 * @mbggenerated
	 */
	public void setBroker_id(Long broker_id) {
		this.broker_id = broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.pack_no
	 * @return  the value of t_succeed_deal.pack_no
	 * @mbggenerated
	 */
	public String getPack_no() {
		return pack_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.pack_no
	 * @param pack_no  the value for t_succeed_deal.pack_no
	 * @mbggenerated
	 */
	public void setPack_no(String pack_no) {
		this.pack_no = pack_no == null ? null : pack_no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.rental
	 * @return  the value of t_succeed_deal.rental
	 * @mbggenerated
	 */
	public Integer getRental() {
		return rental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.rental
	 * @param rental  the value for t_succeed_deal.rental
	 * @mbggenerated
	 */
	public void setRental(Integer rental) {
		this.rental = rental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.brokerage
	 * @return  the value of t_succeed_deal.brokerage
	 * @mbggenerated
	 */
	public Integer getBrokerage() {
		return brokerage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.brokerage
	 * @param brokerage  the value for t_succeed_deal.brokerage
	 * @mbggenerated
	 */
	public void setBrokerage(Integer brokerage) {
		this.brokerage = brokerage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.land_certificate
	 * @return  the value of t_succeed_deal.land_certificate
	 * @mbggenerated
	 */
	public String getLand_certificate() {
		return land_certificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.land_certificate
	 * @param land_certificate  the value for t_succeed_deal.land_certificate
	 * @mbggenerated
	 */
	public void setLand_certificate(String land_certificate) {
		this.land_certificate = land_certificate == null ? null : land_certificate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.certificate_of_title
	 * @return  the value of t_succeed_deal.certificate_of_title
	 * @mbggenerated
	 */
	public String getCertificate_of_title() {
		return certificate_of_title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.certificate_of_title
	 * @param certificate_of_title  the value for t_succeed_deal.certificate_of_title
	 * @mbggenerated
	 */
	public void setCertificate_of_title(String certificate_of_title) {
		this.certificate_of_title = certificate_of_title == null ? null : certificate_of_title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.supplement
	 * @return  the value of t_succeed_deal.supplement
	 * @mbggenerated
	 */
	public String getSupplement() {
		return supplement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.supplement
	 * @param supplement  the value for t_succeed_deal.supplement
	 * @mbggenerated
	 */
	public void setSupplement(String supplement) {
		this.supplement = supplement == null ? null : supplement.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_a_phone
	 * @return  the value of t_succeed_deal.party_a_phone
	 * @mbggenerated
	 */
	public String getParty_a_phone() {
		return party_a_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_a_phone
	 * @param party_a_phone  the value for t_succeed_deal.party_a_phone
	 * @mbggenerated
	 */
	public void setParty_a_phone(String party_a_phone) {
		this.party_a_phone = party_a_phone == null ? null : party_a_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_a_name
	 * @return  the value of t_succeed_deal.party_a_name
	 * @mbggenerated
	 */
	public String getParty_a_name() {
		return party_a_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_a_name
	 * @param party_a_name  the value for t_succeed_deal.party_a_name
	 * @mbggenerated
	 */
	public void setParty_a_name(String party_a_name) {
		this.party_a_name = party_a_name == null ? null : party_a_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_a_sex
	 * @return  the value of t_succeed_deal.party_a_sex
	 * @mbggenerated
	 */
	public Integer getParty_a_sex() {
		return party_a_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_a_sex
	 * @param party_a_sex  the value for t_succeed_deal.party_a_sex
	 * @mbggenerated
	 */
	public void setParty_a_sex(Integer party_a_sex) {
		this.party_a_sex = party_a_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_a_id_number
	 * @return  the value of t_succeed_deal.party_a_id_number
	 * @mbggenerated
	 */
	public String getParty_a_id_number() {
		return party_a_id_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_a_id_number
	 * @param party_a_id_number  the value for t_succeed_deal.party_a_id_number
	 * @mbggenerated
	 */
	public void setParty_a_id_number(String party_a_id_number) {
		this.party_a_id_number = party_a_id_number == null ? null : party_a_id_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_a_address
	 * @return  the value of t_succeed_deal.party_a_address
	 * @mbggenerated
	 */
	public String getParty_a_address() {
		return party_a_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_a_address
	 * @param party_a_address  the value for t_succeed_deal.party_a_address
	 * @mbggenerated
	 */
	public void setParty_a_address(String party_a_address) {
		this.party_a_address = party_a_address == null ? null : party_a_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_b_user_id
	 * @return  the value of t_succeed_deal.party_b_user_id
	 * @mbggenerated
	 */
	public Long getParty_b_user_id() {
		return party_b_user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_b_user_id
	 * @param party_b_user_id  the value for t_succeed_deal.party_b_user_id
	 * @mbggenerated
	 */
	public void setParty_b_user_id(Long party_b_user_id) {
		this.party_b_user_id = party_b_user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_b_sex
	 * @return  the value of t_succeed_deal.party_b_sex
	 * @mbggenerated
	 */
	public Integer getParty_b_sex() {
		return party_b_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_b_sex
	 * @param party_b_sex  the value for t_succeed_deal.party_b_sex
	 * @mbggenerated
	 */
	public void setParty_b_sex(Integer party_b_sex) {
		this.party_b_sex = party_b_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succeed_deal.party_b_id_number
	 * @return  the value of t_succeed_deal.party_b_id_number
	 * @mbggenerated
	 */
	public String getParty_b_id_number() {
		return party_b_id_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succeed_deal.party_b_id_number
	 * @param party_b_id_number  the value for t_succeed_deal.party_b_id_number
	 * @mbggenerated
	 */
	public void setParty_b_id_number(String party_b_id_number) {
		this.party_b_id_number = party_b_id_number == null ? null : party_b_id_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succeed_deal
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SucceedDeal other = (SucceedDeal) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getHouse_id() == null ? other.getHouse_id() == null
						: this.getHouse_id().equals(other.getHouse_id()))
				&& (this.getSucceed_time() == null ? other.getSucceed_time() == null
						: this.getSucceed_time().equals(other.getSucceed_time()))
				&& (this.getRent_start_time() == null ? other.getRent_start_time() == null
						: this.getRent_start_time().equals(other.getRent_start_time()))
				&& (this.getRent_end_time() == null ? other.getRent_end_time() == null
						: this.getRent_end_time().equals(other.getRent_end_time()))
				&& (this.getBroker_id() == null ? other.getBroker_id() == null
						: this.getBroker_id().equals(other.getBroker_id()))
				&& (this.getPack_no() == null ? other.getPack_no() == null
						: this.getPack_no().equals(other.getPack_no()))
				&& (this.getRental() == null ? other.getRental() == null : this.getRental().equals(other.getRental()))
				&& (this.getBrokerage() == null ? other.getBrokerage() == null
						: this.getBrokerage().equals(other.getBrokerage()))
				&& (this.getLand_certificate() == null ? other.getLand_certificate() == null
						: this.getLand_certificate().equals(other.getLand_certificate()))
				&& (this.getCertificate_of_title() == null ? other.getCertificate_of_title() == null
						: this.getCertificate_of_title().equals(other.getCertificate_of_title()))
				&& (this.getSupplement() == null ? other.getSupplement() == null
						: this.getSupplement().equals(other.getSupplement()))
				&& (this.getParty_a_phone() == null ? other.getParty_a_phone() == null
						: this.getParty_a_phone().equals(other.getParty_a_phone()))
				&& (this.getParty_a_name() == null ? other.getParty_a_name() == null
						: this.getParty_a_name().equals(other.getParty_a_name()))
				&& (this.getParty_a_sex() == null ? other.getParty_a_sex() == null
						: this.getParty_a_sex().equals(other.getParty_a_sex()))
				&& (this.getParty_a_id_number() == null ? other.getParty_a_id_number() == null
						: this.getParty_a_id_number().equals(other.getParty_a_id_number()))
				&& (this.getParty_a_address() == null ? other.getParty_a_address() == null
						: this.getParty_a_address().equals(other.getParty_a_address()))
				&& (this.getParty_b_user_id() == null ? other.getParty_b_user_id() == null
						: this.getParty_b_user_id().equals(other.getParty_b_user_id()))
				&& (this.getParty_b_sex() == null ? other.getParty_b_sex() == null
						: this.getParty_b_sex().equals(other.getParty_b_sex()))
				&& (this.getParty_b_id_number() == null ? other.getParty_b_id_number() == null
						: this.getParty_b_id_number().equals(other.getParty_b_id_number()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succeed_deal
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getHouse_id() == null) ? 0 : getHouse_id().hashCode());
		result = prime * result + ((getSucceed_time() == null) ? 0 : getSucceed_time().hashCode());
		result = prime * result + ((getRent_start_time() == null) ? 0 : getRent_start_time().hashCode());
		result = prime * result + ((getRent_end_time() == null) ? 0 : getRent_end_time().hashCode());
		result = prime * result + ((getBroker_id() == null) ? 0 : getBroker_id().hashCode());
		result = prime * result + ((getPack_no() == null) ? 0 : getPack_no().hashCode());
		result = prime * result + ((getRental() == null) ? 0 : getRental().hashCode());
		result = prime * result + ((getBrokerage() == null) ? 0 : getBrokerage().hashCode());
		result = prime * result + ((getLand_certificate() == null) ? 0 : getLand_certificate().hashCode());
		result = prime * result + ((getCertificate_of_title() == null) ? 0 : getCertificate_of_title().hashCode());
		result = prime * result + ((getSupplement() == null) ? 0 : getSupplement().hashCode());
		result = prime * result + ((getParty_a_phone() == null) ? 0 : getParty_a_phone().hashCode());
		result = prime * result + ((getParty_a_name() == null) ? 0 : getParty_a_name().hashCode());
		result = prime * result + ((getParty_a_sex() == null) ? 0 : getParty_a_sex().hashCode());
		result = prime * result + ((getParty_a_id_number() == null) ? 0 : getParty_a_id_number().hashCode());
		result = prime * result + ((getParty_a_address() == null) ? 0 : getParty_a_address().hashCode());
		result = prime * result + ((getParty_b_user_id() == null) ? 0 : getParty_b_user_id().hashCode());
		result = prime * result + ((getParty_b_sex() == null) ? 0 : getParty_b_sex().hashCode());
		result = prime * result + ((getParty_b_id_number() == null) ? 0 : getParty_b_id_number().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succeed_deal
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", house_id=").append(house_id);
		sb.append(", succeed_time=").append(succeed_time);
		sb.append(", rent_start_time=").append(rent_start_time);
		sb.append(", rent_end_time=").append(rent_end_time);
		sb.append(", broker_id=").append(broker_id);
		sb.append(", pack_no=").append(pack_no);
		sb.append(", rental=").append(rental);
		sb.append(", brokerage=").append(brokerage);
		sb.append(", land_certificate=").append(land_certificate);
		sb.append(", certificate_of_title=").append(certificate_of_title);
		sb.append(", supplement=").append(supplement);
		sb.append(", party_a_phone=").append(party_a_phone);
		sb.append(", party_a_name=").append(party_a_name);
		sb.append(", party_a_sex=").append(party_a_sex);
		sb.append(", party_a_id_number=").append(party_a_id_number);
		sb.append(", party_a_address=").append(party_a_address);
		sb.append(", party_b_user_id=").append(party_b_user_id);
		sb.append(", party_b_sex=").append(party_b_sex);
		sb.append(", party_b_id_number=").append(party_b_id_number);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}