package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class SuccedDealCost implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.succed_id
	 * @mbggenerated
	 */
	private Long succed_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.cost_types
	 * @mbggenerated
	 */
	private Integer cost_types;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.expense_item
	 * @mbggenerated
	 */
	private Integer expense_item;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.pay_person
	 * @mbggenerated
	 */
	private Integer pay_person;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.pay_tiem
	 * @mbggenerated
	 */
	private Date pay_tiem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_succed_deal_cost.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_succed_deal_cost
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.id
	 * @return  the value of t_succed_deal_cost.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.id
	 * @param id  the value for t_succed_deal_cost.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.succed_id
	 * @return  the value of t_succed_deal_cost.succed_id
	 * @mbggenerated
	 */
	public Long getSucced_id() {
		return succed_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.succed_id
	 * @param succed_id  the value for t_succed_deal_cost.succed_id
	 * @mbggenerated
	 */
	public void setSucced_id(Long succed_id) {
		this.succed_id = succed_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.cost_types
	 * @return  the value of t_succed_deal_cost.cost_types
	 * @mbggenerated
	 */
	public Integer getCost_types() {
		return cost_types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.cost_types
	 * @param cost_types  the value for t_succed_deal_cost.cost_types
	 * @mbggenerated
	 */
	public void setCost_types(Integer cost_types) {
		this.cost_types = cost_types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.expense_item
	 * @return  the value of t_succed_deal_cost.expense_item
	 * @mbggenerated
	 */
	public Integer getExpense_item() {
		return expense_item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.expense_item
	 * @param expense_item  the value for t_succed_deal_cost.expense_item
	 * @mbggenerated
	 */
	public void setExpense_item(Integer expense_item) {
		this.expense_item = expense_item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.pay_person
	 * @return  the value of t_succed_deal_cost.pay_person
	 * @mbggenerated
	 */
	public Integer getPay_person() {
		return pay_person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.pay_person
	 * @param pay_person  the value for t_succed_deal_cost.pay_person
	 * @mbggenerated
	 */
	public void setPay_person(Integer pay_person) {
		this.pay_person = pay_person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.pay_tiem
	 * @return  the value of t_succed_deal_cost.pay_tiem
	 * @mbggenerated
	 */
	public Date getPay_tiem() {
		return pay_tiem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.pay_tiem
	 * @param pay_tiem  the value for t_succed_deal_cost.pay_tiem
	 * @mbggenerated
	 */
	public void setPay_tiem(Date pay_tiem) {
		this.pay_tiem = pay_tiem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.remark
	 * @return  the value of t_succed_deal_cost.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.remark
	 * @param remark  the value for t_succed_deal_cost.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_succed_deal_cost.money
	 * @return  the value of t_succed_deal_cost.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_succed_deal_cost.money
	 * @param money  the value for t_succed_deal_cost.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succed_deal_cost
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SuccedDealCost other = (SuccedDealCost) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getSucced_id() == null ? other.getSucced_id() == null
						: this.getSucced_id().equals(other.getSucced_id()))
				&& (this.getCost_types() == null ? other.getCost_types() == null
						: this.getCost_types().equals(other.getCost_types()))
				&& (this.getExpense_item() == null ? other.getExpense_item() == null
						: this.getExpense_item().equals(other.getExpense_item()))
				&& (this.getPay_person() == null ? other.getPay_person() == null
						: this.getPay_person().equals(other.getPay_person()))
				&& (this.getPay_tiem() == null ? other.getPay_tiem() == null
						: this.getPay_tiem().equals(other.getPay_tiem()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succed_deal_cost
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getSucced_id() == null) ? 0 : getSucced_id().hashCode());
		result = prime * result + ((getCost_types() == null) ? 0 : getCost_types().hashCode());
		result = prime * result + ((getExpense_item() == null) ? 0 : getExpense_item().hashCode());
		result = prime * result + ((getPay_person() == null) ? 0 : getPay_person().hashCode());
		result = prime * result + ((getPay_tiem() == null) ? 0 : getPay_tiem().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_succed_deal_cost
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", succed_id=").append(succed_id);
		sb.append(", cost_types=").append(cost_types);
		sb.append(", expense_item=").append(expense_item);
		sb.append(", pay_person=").append(pay_person);
		sb.append(", pay_tiem=").append(pay_tiem);
		sb.append(", remark=").append(remark);
		sb.append(", money=").append(money);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}