package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class UserFollowUp implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_follow_up.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_follow_up.user_id
	 * @mbggenerated
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_follow_up.broker_id
	 * @mbggenerated
	 */
	private Long broker_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_follow_up.content
	 * @mbggenerated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_follow_up.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_follow_up
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_follow_up.id
	 * @return  the value of t_user_follow_up.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_follow_up.id
	 * @param id  the value for t_user_follow_up.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_follow_up.user_id
	 * @return  the value of t_user_follow_up.user_id
	 * @mbggenerated
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_follow_up.user_id
	 * @param user_id  the value for t_user_follow_up.user_id
	 * @mbggenerated
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_follow_up.broker_id
	 * @return  the value of t_user_follow_up.broker_id
	 * @mbggenerated
	 */
	public Long getBroker_id() {
		return broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_follow_up.broker_id
	 * @param broker_id  the value for t_user_follow_up.broker_id
	 * @mbggenerated
	 */
	public void setBroker_id(Long broker_id) {
		this.broker_id = broker_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_follow_up.content
	 * @return  the value of t_user_follow_up.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_follow_up.content
	 * @param content  the value for t_user_follow_up.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_follow_up.time
	 * @return  the value of t_user_follow_up.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_follow_up.time
	 * @param time  the value for t_user_follow_up.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_follow_up
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserFollowUp other = (UserFollowUp) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUser_id() == null ? other.getUser_id() == null
						: this.getUser_id().equals(other.getUser_id()))
				&& (this.getBroker_id() == null ? other.getBroker_id() == null
						: this.getBroker_id().equals(other.getBroker_id()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_follow_up
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUser_id() == null) ? 0 : getUser_id().hashCode());
		result = prime * result + ((getBroker_id() == null) ? 0 : getBroker_id().hashCode());
		result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_follow_up
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", user_id=").append(user_id);
		sb.append(", broker_id=").append(broker_id);
		sb.append(", content=").append(content);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}