package com.yqwl.dao;

import com.yqwl.pojo.Administrator;

public interface AdministratorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	int insert(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	int insertSelective(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	Administrator selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_administrator
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Administrator record);
}