package com.yqwl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.Vo.AttentionVo;
import com.yqwl.pojo.Attention;

public interface AttentionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int insert(Attention record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int insertSelective(Attention record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	Attention selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Attention record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attention
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Attention record);
	/**
	 * @Title: selectFinfAll
	 * @description 查询id用于查重
	 * @param @param record
	 * @param @return    
	 * @return Attention    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	Attention selectFinfAll(Attention record);
	/**
	 * @Title: selectScend
	 * @description 查询收藏的商厦信息
	 * @param @param records
	 * @param @return    
	 * @return List<AttentionVo>    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	List<AttentionVo> selectScend(AttentionVo records);
	/**
	 * @Title: selectThird
	 * @description 查询收藏的房源信息
	 * @param @param records
	 * @param @return    
	 * @return List<AttentionVo>    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	List<AttentionVo> selectThird(AttentionVo records);
	/**
	 * @Title: selectCount
	 * @description 查询收藏数据条数
	 * @param @param records
	 * @param @return    
	 * @return Integer    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	Integer selectCount(AttentionVo records);
	/**
	 * @Title: selectAtten
	 * @description 查询该商厦是否被收藏
	 * @param @param houses_new_id
	 * @param @return    
	 * @return List<Attention>    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	List<Attention> selectAtten(Long houses_new_id);

	int delByHousesId(Long homeId);
	/**
	 * @Title: selectInfor
	 * @description 查询该房源或商厦是否已收藏
	 * @param @param user_phone
	 * @param @param houses_new_id
	 * @param @param type
	 * @param @return    
	 * @return Attention    
	 * @author linhongyu
	 * @createDate 2019年7月11日
	 */
	Attention selectInfor(@Param("user_phone")Long user_phone,@Param("houses_new_id")Long houses_new_id,@Param("type")int type);
	/**
	 * @Title: deletTnfor
	 * @description 前台页面取消收藏
	 * @param @param user_phone
	 * @param @param houses_new_id
	 * @param @param type
	 * @param @return    
	 * @return int    
	 * @author linhongyu
	 * @createDate 2019年7月11日
	 */
	int deletTnfor(@Param("user_phone")Long user_phone,@Param("houses_new_id")Long houses_new_id,@Param("type")int type);
}