package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.BrokerRole;

public interface BrokerRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    int insert(BrokerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    int insertSelective(BrokerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    BrokerRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrokerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_broker_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrokerRole record);

	int delByBrokerId(Long brokerId);

	List<BrokerRole> listByRoleId(Long id);
}