package com.yqwl.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.pojo.Broker;

public interface BrokerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int insert(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int insertSelective(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	Broker selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Broker record);

	Broker getByUserNameAndPassword(@Param("userName")String userName,@Param("password")String password);

	Long getBrokerByCityId(Long group_id);
	/**
	 * @Title: listAll
	 * @description 查询所有经纪人
	 * @param @return    
	 * @return List<Broker>    
	 * @author linhongyu
	 * @createDate 2019年4月29日
	 */
	List<Broker> listAll();

	Long getBrokerByShopId(Long id);

	List<Broker> getBrokerByGroupId(Long groupId);

	List<Broker> listAllByStatus(@Param("status")Integer status,@Param("cityId")Integer cityId);

	List<Broker> listByCondition(@Param("condition")String condition, @Param("state")Long state);

}