package com.yqwl.dao;

import com.yqwl.pojo.Broker;

public interface BrokerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int insert(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int insertSelective(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	Broker selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Broker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broker
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Broker record);
}