package com.yqwl.dao;

import com.yqwl.pojo.Building;

public interface BuildingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int insert(Building record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int insertSelective(Building record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	Building selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Building record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_building
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Building record);
}