package com.yqwl.dao;

import java.math.BigInteger;

import com.yqwl.pojo.Client;

public interface ClientMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int insert(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int insertSelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	Client selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Client record);
	
	Client seleceFindId(Long phones);
}