package com.yqwl.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yqwl.Vo.ClientVo;
import com.yqwl.pojo.Client;
public interface ClientMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int insert(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int insertSelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	Client selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Client record);
	/**
	 * @Title: seleceFindId
	 * @description 通过手机号查询
	 * @param @param phones
	 * @param @return    
	 * @return Client    
	 * @author linhongyu
	 * @createDate 2019年4月29日
	 */
	Client seleceFindId(Long phones);
	/**
	 * @Title: selectClient
	 * @description 查询客户列表并分页
	 * @param @param page
	 * @param @param limit
	 * @param @return    
	 * @return List<Client>    
	 * @author linhongyu
	 * @createDate 2019年5月5日
	 */
	List<ClientVo> selectClient(@Param("page") Integer page,@Param("limit") Integer limit);
	/**
	 * @Title: selectCount
	 * @description 查询客户列表条数
	 * @param @return    
	 * @return Integer    
	 * @author linhongyu
	 * @createDate 2019年5月5日
	 */
	Integer selectCount();
}