package com.yqwl.dao;

import java.util.List;

import com.yqwl.Vo.EntrustseeVo;
import com.yqwl.pojo.Entrustsee;

public interface EntrustseeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int insert(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int insertSelective(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	Entrustsee selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Entrustsee record);
	/**
	 * 修改预约看房状态
	 */
	int updateType(Entrustsee record);
	/**
	 * 后台查询所有预约看房
	 */
	List<EntrustseeVo> selectAllEN(EntrustseeVo record);

	Integer getByHousesNewIdCount(Long id);
}