package com.yqwl.dao;

import com.yqwl.pojo.Entrustsee;

public interface EntrustseeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int insert(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int insertSelective(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	Entrustsee selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Entrustsee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_entrustsee
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Entrustsee record);
}