package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Existing;

public interface ExistingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    int insert(Existing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    int insertSelective(Existing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    Existing selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Existing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_existing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Existing record);

	List<Existing> homePageCity();
}