package com.yqwl.dao;

import java.util.List;

import com.yqwl.Vo.FeedbackVo;
import com.yqwl.pojo.Feedback;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    Feedback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Feedback record);
    /**
     * @Title: selectListKey
     * @description 查询该房源的反馈信息
     * @param @param home_id
     * @param @return    
     * @return List<Feedback>    
     * @author linhongyu
     * @createDate 2019年6月12日
     */
    List<FeedbackVo> selectListKey(Long hone_id);
}