package com.yqwl.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.Vo.FollowUpVo;
import com.yqwl.pojo.FollowUp;

import net.sf.jsqlparser.statement.select.Select;

public interface FollowUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    int insert(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    int insertSelective(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    FollowUp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_up
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FollowUp record);
    /**
     * @Title: selectFollow
     * @description 通过经纪人id查询跟进信息
     * @param @param broker_id
     * @param @return    
     * @return FollowUp    
     * @author linhongyu
     * @createDate 2019年6月10日
     */
    FollowUp selectFollow(@Param("broker_id") Long broker_id);
    /**
     * @Title: selectHomeId
     * @description 查询该房源的跟进信息
     * @param @param home_id
     * @param @return    
     * @return FollowUpVo    
     * @author linhongyu
     * @createDate 2019年6月11日
     */
    List<FollowUpVo> selectHomeId(@Param("home_id") Long home_id);
    /**
     * @Title: selectFollowCount
     * @description 查询经纪人房源跟进条数
     * @param @param broker_id
     * @param @return    
     * @return int    
     * @author linhongyu
     * @createDate 2019年7月10日
     */
    int selectFollowCount(@Param("broker_id") Long broker_id,@Param("startTime") Date startTime,@Param("endTime") Date endTime);
}