package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Function;

public interface FunctionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	int insert(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	int insertSelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	Function selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_function
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Function record);

	List<Function> getFunctionByRoleId(Long roleId);

	List<Function> listAll();
}