package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.FuncRole;
import com.yqwl.pojo.Function;

public interface FuncRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    int insert(FuncRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    int insertSelective(FuncRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    FuncRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FuncRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FuncRole record);

	List<FuncRole> listByRoleId(Long roleId);

	int delByRoleId(Long roleId);
}