package com.yqwl.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.yqwl.pojo.HomePageRecommended;
public interface HomePageRecommendedMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	int insert(HomePageRecommended record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	int insertSelective(HomePageRecommended record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	HomePageRecommended selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HomePageRecommended record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_home_page_recommended
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HomePageRecommended record);

	List<HomePageRecommended> listByType(Integer type);

	/**
	 *
	 * @Title: selectRecommended
	 * @description 查询是否首页推荐
	 * @param @param building_id    
	 * @return void    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	HomePageRecommended selectRecommended(Long building_id);

	List<HomePageRecommended> listByTypeAndCityId(@Param("type")Integer type,@Param("cityId") Integer cityId);
	
    
}