package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.HomePageRecommended;

public interface HomePageRecommendedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    int insert(HomePageRecommended record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    int insertSelective(HomePageRecommended record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    HomePageRecommended selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HomePageRecommended record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_home_page_recommended
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HomePageRecommended record);

	List<HomePageRecommended> listByType(Integer type);
	
    
}