package com.yqwl.dao;


import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.Vo.HousesNewVo;
import com.yqwl.pojo.HousesNew;

public interface HousesNewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int insert(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int insertSelective(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	HousesNew selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HousesNew record);

	public HousesNewVo selectByFindID(long id);

	List<HousesNew> listHousesNewByCondition(@Param("cityId")Integer cityId , @Param("regionId")Integer regionId,@Param("startSpace") Integer startSpace,@Param("endSpace") Integer endSpace,@Param("startMoney") BigDecimal startMoney,
			@Param("endMoney")BigDecimal endMoney,@Param("fitment") Integer fitment,@Param("brokerId") Integer brokerId,@Param("phone") String phone,@Param("ownerName") String ownerName, @Param("buildingId") Integer buildingId);
	/*查询可能喜欢的房源信�?????**/
	List<HousesNewVo> selectLike(HousesNewVo record);

	List<HousesNew> listHousesNewByBuildingId(Long buildingId);
	/**
	 * @Title: selectHousesNew
	 * @description 查询该商厦下的房�???
	 * @param @param buildingId
	 * @param @return    
	 * @return List<HousesNew>    
	 * @author linhongyu
	 * @createDate 2019�?4�?30�?
	 */
	List<HousesNew> selectHousesNew(Long buildingId);

	List<HousesNew> ListBackHousesNew(@Param("cityId")Integer cityId , @Param("regionId")Integer regionId,@Param("startSpace") Integer startSpace,@Param("endSpace") Integer endSpace,@Param("startMoney") BigDecimal startMoney,
			@Param("endMoney")BigDecimal endMoney,@Param("fitment") Integer fitment,@Param("shopId") Long shopId,@Param("brokerId") Integer brokerId,@Param("phone") String phoneOrName,@Param("ownerName") String ownerName,@Param("buildingId") Integer buildingId);

	List<HousesNew> listByShopId(Long id);
	/**
	 * @Title: updateSelective
	 * @description 修改房源状�?�活�?盘修�?
	 * @param @param record
	 * @param @return    
	 * @return int    
	 * @author linhongyu
	 * @createDate 2019�?6�?12�?
	 */
	int updateSelective(HousesNew record);

}