package com.yqwl.dao;


import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.Vo.HousesNewVo;
import com.yqwl.pojo.HousesNew;

public interface HousesNewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int insert(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int insertSelective(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	HousesNew selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HousesNew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_houses_new
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HousesNew record);

	public HousesNewVo selectByFindID(long id);

	List<HousesNew> listHousesNewByCondition(@Param("cityId")Integer cityId , @Param("regionId")Integer regionId,@Param("startSpace") Integer startSpace,@Param("endSpace") Integer endSpace,@Param("startMoney") BigDecimal startMoney,
			@Param("endMoney")BigDecimal endMoney,@Param("fitment") Integer fitment);
	/*查询可能喜欢的房源信�??**/
	List<HousesNewVo> selectLike(HousesNewVo record);

	List<HousesNew> listHousesNewByBuildingId(Long buildingId);
	/**
	 * @Title: selectHousesNew
	 * @description 查询该商厦下的房源
	 * @param @param buildingId
	 * @param @return    
	 * @return List<HousesNew>    
	 * @author linhongyu
	 * @createDate 2019年4月30日
	 */
	List<HousesNew> selectHousesNew(Long buildingId);

	List<HousesNew> ListBackHousesNew(@Param("cityId")Integer cityId , @Param("regionId")Integer regionId,@Param("startSpace") Integer startSpace,@Param("endSpace") Integer endSpace,@Param("startMoney") BigDecimal startMoney,
			@Param("endMoney")BigDecimal endMoney,@Param("fitment") Integer fitment,@Param("shopId") Long shopId);

	List<HousesNew> listByShopId(Long id);

}