package com.yqwl.dao;

import com.yqwl.pojo.Leaser;

public interface LeaserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	int insert(Leaser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	int insertSelective(Leaser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	Leaser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Leaser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leaser
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Leaser record);
}