package com.yqwl.dao;

import com.yqwl.pojo.NewsPic;

public interface NewsPicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	int insert(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	int insertSelective(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	NewsPic selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_pic
	 * @mbggenerated
	 */
	int updateByPrimaryKey(NewsPic record);
}