package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Owner;

public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    int insert(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    int insertSelective(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    Owner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Owner record);
    /**
     * 
     * @Title: selectHome
     * @description 通过房源ID查询业主电话
     * @param @param id
     * @param @return    
     * @return List<Owner>    
     * @author linhongyu
     * @createDate 2019年7月5日
     */
    List<Owner> selectHome(Long id);
}