package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Photo;

public interface PhotoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	int insert(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	int insertSelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	Photo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_photo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Photo record);
	public List<Photo> selectPhoto(long id);
	List<Photo> listByBuildingId(Long buildingId);
}