package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Picture;

public interface PictureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	int insert(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	int insertSelective(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	Picture selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Picture record);
	public List<Picture> selectPic(long id);
}