package com.yqwl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.pojo.PlotBuild;
import com.yqwl.pojo.PlotDoor;

public interface PlotDoorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	int insert(PlotDoor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	int insertSelective(PlotDoor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	PlotDoor selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlotDoor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_door
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlotDoor record);

	List<PlotDoor> getPlotDoorByConditions(Long buildId);

	int deleteByBuildId(Long id);

	List<PlotDoor> getPlotDoorByFloor(@Param("buildId")Long buildId, @Param("floor")Integer floor);

	int deletePlotDoorByFloor(@Param("buildId")Long buildId, @Param("floor")Integer floor);
}