package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.PlotBuild;

public interface PlotBuildMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	int insert(PlotBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	int insertSelective(PlotBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	PlotBuild selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PlotBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_plot_build
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PlotBuild record);

	List<PlotBuild> getPlotBuildByConditions(Long buildingId);
}