package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Role;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	Role selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Role record);

	List<Role> getBrokerByRole(Long brokerId);

	List<Role> listAllRole();
}