package com.yqwl.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.Vo.UserListVo;
import com.yqwl.Vo.UserVo;
import com.yqwl.pojo.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);
	List<UserVo> listAll(@Param("name")String name,@Param("category") Integer category);
	/**
	 * @Title: selectListShop
	 * @description 通过区县id查询分店id
	 * @param @param region_id
	 * @param @return    
	 * @return List<User>    
	 * @author linhongyu
	 * @createDate 2019�??6�??13�??
	 */
	List<User> selectListShop(Long region_id);
	/**
	 * @Title: selectAllSome
	 * @description 添加决策分析(根据条件查询相关经纪人客源统计)
	 * @param @param id
	 * @param @param category
	 * @param @param startTime
	 * @param @param endTime
	 * @param @return    
	 * @return int    
	 * @author linhongyu
	 * @createDate 2019�??6�??17�??
	 */
	int selectAllSome(@Param("id")Long id, @Param("category")int category, @Param("startTime")Date startTime, @Param("endTime")Date endTime);
	
	List<User> findAll();
	
	List<User> listByBrokerId(Long brokerId);
	
	List<UserVo> listAllByShop(@Param("name")String name,@Param("category") Integer category,@Param("shopId") Long shopId);
	
	List<User> listAllByBrokerId(@Param("name")String name,@Param("category") Integer category,@Param("brokerId") Long brokerId);

}